// Package image is `pstack build-image` — build the control image from the installed package itself.
//
// WHY THIS EXISTS. `pstack init` requires the control image to exist locally and deliberately does
// not pull. That left a globally-installed pstack in a dead end: the published package ships only
// `dist/`, so there was no Dockerfile to build from and no registry to pull from — `init` would
// refuse with "image pstack:local not found" and the operator's only way out was cloning the
// source. A CLI that cannot produce the one artefact it requires is a broken install.
//
// The way out: the Dockerfile INSTALLS THE PUBLISHED PACKAGE inside the build. No checkout, no
// registry for the image, and — the part that matters — nothing needs to be present on the host
// beyond docker itself. The build context is empty; the Dockerfile arrives on stdin.
//
// That is what makes the advanced UI work too. It is a build-time input to its image, so requiring
// it to ALSO be installed globally on the host was gratuitous — and on a host where `bun install -g`
// fails (no global directory), it turned an optional UI into a boot failure.
//
// `--dist-dir` / `--ui-dist` keep the old behaviour of building from local files, for developing a
// change that is not published yet.
//
// The generated image is byte-identical in behaviour to the repo's own Dockerfile runtime stage —
// that file keeps the multi-stage source build for CI and contributors; this is the same final
// layer, fed from an already-built bundle.
//
// PORT NOTE: the Dockerfiles' CONTENT is what the TypeScript emits today (the bun-based runtime,
// the `pstack healthcheck` HEALTHCHECK). The packaging redesign is a later phase; the conformance
// goldens drop these lines in go mode (`goDivergent`) until it lands.
package image

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/samishal1998/preview-stacks/packages/pstack/internal/exec"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/js"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/jsonx"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/swarm"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/version"
)

// DefaultImageTag is the control image's tag.
const DefaultImageTag = "pstack:local"

// DefaultUIImageTag matches PSTACK_UI_IMAGE's default in `init`, so `build-image --ui` then
// `init --ui advanced` need no flags between them.
const DefaultUIImageTag = "pstack-ui:local"

// ControlDockerfile is the control image, built by installing this exact version from npm.
//
// Pinned to the running CLI's version so the image and the CLI that rendered it cannot disagree —
// an image floating on `latest` would silently drift from the `init` that deployed it.
//
// The entry point is the file inside node_modules rather than a global bin: `bun install -g` needs
// a writable global directory that not every image or host provides, and when it is missing the
// failure is an opaque "No global directory found" at runtime.
func ControlDockerfile(ver string) string {
	if ver == "" {
		ver = version.Get()
	}
	return "# Generated by `pstack dockerfile` (pstack " + ver + `). Rewritten on every run.
#
# Self-contained: builds with an EMPTY context, so ` + "`docker build -t pstack:local - < this-file`" + `
# works on a host with nothing but docker.

# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# ~50 MB instead of ~200 MB and no key/repo dance. pstack drives ` + "`docker compose`" + ` by shelling out,
# so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM oven/bun:1

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: ` + "`docker compose`" + ` resolves ` + "`docker-compose`" + ` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Client-side, needs no daemon: turns a moved upstream path into an obvious build failure rather
# than a runtime one on the host.
RUN docker --version && docker compose version

WORKDIR /app
RUN bun add @samyx/preview-stacks@` + ver + `

# Non-root by default. The control stack overrides it with ` + "`user: \"0:0\"`" + ` because it mounts the
# Docker socket read-write.
USER bun

EXPOSE 7878

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD ["bun", "node_modules/@samyx/preview-stacks/dist/cli.js", "healthcheck"]

CMD ["bun", "node_modules/@samyx/preview-stacks/dist/cli.js", "serve"]
`
}

// UIDockerfile is the advanced UI image: nginx over the published SPA package. Also builds with an
// empty context.
func UIDockerfile(ver string) string {
	if ver == "" {
		ver = version.Get()
	}
	return "# Generated by `pstack dockerfile --ui` (pstack " + ver + `). Rewritten on every run.
#
# Self-contained: ` + "`docker build -t pstack-ui:local - < this-file`" + `. The UI package is a BUILD-TIME
# input fetched here, so it never has to be installed on the host.
FROM oven/bun:1 AS fetch
WORKDIR /app
RUN bun add @samyx/preview-stacks-ui@` + ver + `

FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link 404s on reload) and no
# /api/ proxy (every API call would leave the origin and need CORS).
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`
}

func localDockerfile() string {
	return "# Generated by `pstack build-image`. Do not edit — it is rewritten on every run." + `
#
# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# the layer is ~50 MB instead of ~200 MB and needs no key/repo dance. pstack drives ` + "`docker compose`" + `
# by shelling out, so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM oven/bun:1

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: ` + "`docker compose`" + ` resolves ` + "`docker-compose`" + ` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Assert it at BUILD time: client-side, needs no daemon, and turns a moved upstream path into an
# obvious build failure instead of a runtime one on the host.
RUN docker --version && docker compose version

WORKDIR /app

# The whole application: one bundle plus its sourcemap. The UI and the control-stack compose
# template are inlined into it as text imports, so there is nothing to keep as a sibling and no
# path resolved relative to source — the failure mode where an image works from a checkout and
# 404s once installed.
COPY dist ./dist

# Non-root by default. The control stack overrides it with ` + "`user: \"0:0\"`" + ` because it mounts the
# Docker socket read-write.
USER bun

EXPOSE 7878

# Liveness from the API's own route via the CLI's ` + "`healthcheck`" + ` command, so it depends on nothing
# the base image might drop and reads PSTACK_PORT like the server does. ` + "`init`" + ` waits for this to
# report healthy before claiming the control stack is up.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD ["bun", "dist/cli.js", "healthcheck"]

CMD ["bun", "dist/cli.js", "serve"]
`
}

// localUIDockerfile is the local-files variant of the UI image, used only with `--ui-dist`
// (unpublished work in progress).
func localUIDockerfile() string {
	return "# Generated by `pstack build-image --ui`. Do not edit — rewritten on every run." + `
FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link would 404 on reload) and
# no /api/ proxy (every API call would leave the origin and need CORS).
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`
}

// BuildOptions are build-image's inputs.
type BuildOptions struct {
	Tag    string
	Runner exec.Runner
	DryRun bool
	// UI builds the advanced UI image instead of the control-plane image.
	UI bool
	// UIDist is an explicit path to a built UI `dist/`, for when the package is installed somewhere unusual.
	UIDist string
	// DistDir overrides the directory copied into the build context. Defaults to none (the
	// Dockerfile installs the published package).
	//
	// Exists so the logic here — context assembly, the docker invocation, cleanup — can be tested
	// without a build artefact present. A unit test that first requires `bun scripts/build.ts` is
	// order-dependent on a step it does not own, which is exactly how this arrived in CI green
	// locally and red on a clean checkout.
	DistDir string
	// Out is where progress lines go (stdout when nil).
	Out io.Writer
}

// Build assembles a build context from the installed bundle and builds the image.
//
// The context is a temp directory rather than the install directory: an install may live somewhere
// read-only (or shared between projects), and writing a Dockerfile into a package's own directory
// would mutate an installed dependency. It is removed even on failure — a half-built context left
// in /tmp is the sort of litter nobody goes looking for.
func Build(opts BuildOptions) error {
	out := opts.Out
	if out == nil {
		out = os.Stdout
	}
	tag, runner, ui := opts.Tag, opts.Runner, opts.UI
	// DEFAULT: no local files at all. The Dockerfile installs the published package itself, so the
	// host needs nothing but docker — no checkout, and no global install of the UI package just to
	// build an image that was going to fetch it anyway.
	dist := opts.DistDir
	if ui {
		dist = opts.UIDist
	}

	if opts.DryRun {
		if dist != "" {
			fmt.Fprintf(out, "  [dry-run] assemble build context from %s\n", dist)
		}
		fmt.Fprintf(out, "  [dry-run] docker image tag %s %s-previous\n", tag, tag)
		fmt.Fprintf(out, "  [dry-run] docker build -t %s <context>\n", tag)
		return nil
	}

	/*
	 * THE ROLLBACK PATH. `docker build -t pstack:local` moves the tag; the image that was running a
	 * second ago becomes an anonymous `<none>` layer with no handle. If the new build comes up
	 * unhealthy after `init` recreates the stack, the control plane is gone and nothing names the
	 * image that worked. Keeping it under `<tag>-previous` makes recovery one line:
	 *   docker tag pstack:local-previous pstack:local && docker compose -p pstack-control … up -d
	 * Best-effort: on a host with no image yet there is nothing to keep.
	 */
	runner.Run("docker image tag "+swarm.Shq(tag)+" "+swarm.Shq(tag+"-previous")+" 2>/dev/null || true", exec.RunOptions{
		Label: "keep the previous " + tag,
	})

	// The Dockerfile is WRITTEN, never interpolated into a command. It is a multi-KB document full of
	// backticks and `$`, and passing it through a shell — even quoted — lets the shell read it: the
	// backticks in its own comments became command substitutions and spliced `docker compose`'s help
	// text into the middle of the file. A build context is a directory; give docker a directory.
	ctx, err := os.MkdirTemp("", "pstack-image-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(ctx)

	if dist != "" {
		// ESCAPE HATCH: build from local files, for a change that is not published yet.
		if ui && !exists(filepath.Join(dist, "index.html")) {
			return fmt.Errorf("no built UI at %s — expected an index.html there", dist)
		}
		if err := os.CopyFS(filepath.Join(ctx, "dist"), os.DirFS(dist)); err != nil {
			return err
		}
		if ui {
			// The nginx config sits next to `dist/` in the package, not inside it.
			conf := filepath.Join(dist, "..", "nginx.conf")
			if !exists(conf) {
				return fmt.Errorf("found the UI assets at %s but no nginx.conf beside them — the package is "+
					"incomplete, so the image would serve the SPA with no /api proxy and no deep-link "+
					"fallback.", dist)
			}
			b, err := os.ReadFile(conf)
			if err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(ctx, "nginx.conf"), b, 0o666); err != nil {
				return err
			}
		}
	}

	var df string
	switch {
	case dist != "" && ui:
		df = localUIDockerfile()
	case dist != "":
		df = localDockerfile()
	case ui:
		df = UIDockerfile("")
	default:
		df = ControlDockerfile("")
	}
	if err := os.WriteFile(filepath.Join(ctx, "Dockerfile"), []byte(df), 0o666); err != nil {
		return err
	}

	if dist != "" {
		fmt.Fprintf(out, "building %s from %s\n", tag, dist)
	} else {
		fmt.Fprintf(out, "building %s (pstack %s, from npm)\n", tag, version.Get())
	}
	// `--pull` so a months-old cached `oven/bun:1` does not silently pin an old runtime; the base
	// layers are shared with anything else on the box, so the cost is one manifest check.
	// JSON.stringify for the two args, as the TS did — not shq.
	r := runner.Run("docker build --pull -t "+string(jsonx.Must(tag))+" "+string(jsonx.Must(ctx)), exec.RunOptions{
		Label: "docker build " + tag,
	})
	if !r.OK {
		o := r.Stderr
		if o == "" {
			o = r.Stdout
		}
		return fmt.Errorf("docker build failed (exit %d).\n%s", r.Code, js.Truncate(strings.TrimSpace(o), 2000))
	}
	fmt.Fprintf(out, "built %s\n", tag)
	if ui {
		fmt.Fprintln(out, "  next:  pstack init --ui advanced --domain <preview.example.com> --acme-email <you@example.com>")
	} else {
		fmt.Fprintln(out, "  next:  pstack init --domain <preview.example.com> --acme-email <you@example.com>")
	}
	return nil
}

// exists is Bun.file(p).exists(): a regular file (or anything stat-able) at p.
func exists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
