// Package image is `pstack build-image` — build the control image from the running binary itself.
//
// WHY THIS EXISTS. `pstack init` requires the control image to exist locally and deliberately does
// not pull. A CLI that cannot produce the one artefact it requires is a broken install, so the
// image is built HERE, from what is already on the host: pstack is one static binary, and the
// control image is that binary on a slim base with the docker CLI beside it. No checkout, no
// registry, and no second download — the image carries exactly the version that built it.
//
// The build context is a temp directory holding a copy of the running binary (`os.Executable`)
// and the generated Dockerfile. That binary is a Linux one only on Linux, which is where every
// host this ships to runs; on macOS `build-image` refuses and names the two alternatives rather
// than building an image whose entrypoint cannot exec.
//
// The advanced UI image is unchanged in principle: the SPA package is a BUILD-TIME input fetched
// from npm inside the build, so docker — not the host — needs a JavaScript runtime. `--ui-dist`
// keeps the old behaviour of building from local files, for developing a change that is not
// published yet.
package image

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/samishal1998/preview-stacks/packages/pstack/internal/exec"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/js"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/jsonx"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/swarm"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/version"
)

// DefaultImageTag is the control image's tag.
const DefaultImageTag = "pstack:local"

// DefaultUIImageTag matches PSTACK_UI_IMAGE's default in `init`, so `build-image --ui` then
// `init --ui advanced` need no flags between them.
const DefaultUIImageTag = "pstack-ui:local"

// ControlDockerfile is the control image: the pstack binary on debian:bookworm-slim with bash
// (hooks are bash), ca-certificates and curl (the installer, ACME, webhooks), and the docker CLI +
// compose plugin lifted from the official image.
//
// Pinned to the running CLI's version so the image and the CLI that rendered it cannot disagree.
// The context must hold the Linux binary of that version as `pstack` — `build-image` assembles it
// from the running binary; by hand, download `pstack_linux_<arch>` from the release page into an
// empty directory under that name.
func ControlDockerfile(ver string) string {
	if ver == "" {
		ver = version.Get()
	}
	return "# Generated by `pstack dockerfile` (pstack " + ver + `). Rewritten on every run.
#
# Build context: a directory holding the Linux ` + "`pstack`" + ` binary of this exact version, named ` + "`pstack`" + `.
# ` + "`pstack build-image`" + ` assembles one from the running binary; by hand:
#   curl -fsSLo pstack https://github.com/samishal1998/preview-stacks/releases/download/v` + ver + `/pstack_linux_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
#   docker build -t pstack:local -f this-file .

# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# ~50 MB instead of ~200 MB and no key/repo dance. pstack drives ` + "`docker compose`" + ` by shelling out,
# so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM debian:bookworm-slim

# bash: axis hooks are ` + "`bash -c`" + `. ca-certificates + curl: ACME, webhooks, the installer.
RUN apt-get update \
 && apt-get install -y --no-install-recommends bash ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: ` + "`docker compose`" + ` resolves ` + "`docker-compose`" + ` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Client-side, needs no daemon: turns a moved upstream path into an obvious build failure rather
# than a runtime one on the host.
RUN docker --version && docker compose version

# The whole application: one static binary. Asserted at build time so a context holding the
# wrong architecture (or an HTML error page saved as ` + "`pstack`" + `) fails here, not on the host.
COPY pstack /usr/local/bin/pstack
RUN chmod 0755 /usr/local/bin/pstack && /usr/local/bin/pstack --version

# Non-root by default. The control stack overrides it with ` + "`user: \"0:0\"`" + ` because it mounts the
# Docker socket read-write.
RUN useradd --uid 1000 --create-home --shell /bin/bash pstack
WORKDIR /app
USER pstack

EXPOSE 7878

# Liveness from the API's own route via the CLI's ` + "`healthcheck`" + ` command, so it depends on nothing
# the base image might drop and reads PSTACK_PORT like the server does. ` + "`init`" + ` waits for this to
# report healthy before claiming the control stack is up.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD ["pstack", "healthcheck"]

CMD ["pstack", "serve"]
`
}

// UIDockerfile is the advanced UI image: nginx over the published SPA package. Also builds with an
// empty context.
func UIDockerfile(ver string) string {
	if ver == "" {
		ver = version.Get()
	}
	return "# Generated by `pstack dockerfile --ui` (pstack " + ver + `). Rewritten on every run.
#
# Self-contained: ` + "`docker build -t pstack-ui:local - < this-file`" + `. The UI package is a BUILD-TIME
# input fetched here, so it never has to be installed on the host.
FROM oven/bun:1 AS fetch
WORKDIR /app
RUN bun add @samyx/preview-stacks-ui@` + ver + `

FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link 404s on reload) and no
# /api/ proxy (every API call would leave the origin and need CORS).
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`
}

// localUIDockerfile is the local-files variant of the UI image, used only with `--ui-dist`
// (unpublished work in progress).
func localUIDockerfile() string {
	return "# Generated by `pstack build-image --ui`. Do not edit — rewritten on every run." + `
FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link would 404 on reload) and
# no /api/ proxy (every API call would leave the origin and need CORS).
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`
}

// BuildOptions are build-image's inputs.
type BuildOptions struct {
	Tag    string
	Runner exec.Runner
	DryRun bool
	// UI builds the advanced UI image instead of the control-plane image.
	UI bool
	// UIDist is an explicit path to a built UI `dist/`, for when the package is installed somewhere unusual.
	UIDist string
	// Binary is the Linux binary to put in the context as `pstack`. Default: the running
	// executable (Linux only — see Build). A test passes any file; an operator on macOS passes a
	// cross-built one.
	Binary string
	// GOOS overrides runtime.GOOS for the Linux check (tests).
	GOOS string
	// Out is where progress lines go (stdout when nil).
	Out io.Writer
}

// Build assembles a build context from the installed bundle and builds the image.
//
// The context is a temp directory rather than the install directory: an install may live somewhere
// read-only (or shared between projects), and writing a Dockerfile into a package's own directory
// would mutate an installed dependency. It is removed even on failure — a half-built context left
// in /tmp is the sort of litter nobody goes looking for.
func Build(opts BuildOptions) error {
	out := opts.Out
	if out == nil {
		out = os.Stdout
	}
	tag, runner, ui := opts.Tag, opts.Runner, opts.UI
	dist := ""
	if ui {
		dist = opts.UIDist
	}
	binary := opts.Binary
	if !ui && binary == "" {
		goos := opts.GOOS
		if goos == "" {
			goos = runtime.GOOS
		}
		if goos != "linux" {
			return fmt.Errorf("build-image copies the RUNNING pstack binary into the image, and this one is a " + goos + " build " +
				"that cannot exec inside a Linux container. Either build from a checkout (`docker build -t pstack:local .`) " +
				"or download the Linux binary of this version and point at it: `PSTACK_BINARY=<path> pstack build-image`.")
		}
		exe, err := os.Executable()
		if err != nil {
			return err
		}
		binary = exe
	}

	if opts.DryRun {
		if dist != "" {
			fmt.Fprintf(out, "  [dry-run] assemble build context from %s\n", dist)
		} else if !ui {
			fmt.Fprintf(out, "  [dry-run] assemble build context from %s\n", binary)
		}
		fmt.Fprintf(out, "  [dry-run] docker image tag %s %s-previous\n", tag, tag)
		fmt.Fprintf(out, "  [dry-run] docker build -t %s <context>\n", tag)
		return nil
	}

	/*
	 * THE ROLLBACK PATH. `docker build -t pstack:local` moves the tag; the image that was running a
	 * second ago becomes an anonymous `<none>` layer with no handle. If the new build comes up
	 * unhealthy after `init` recreates the stack, the control plane is gone and nothing names the
	 * image that worked. Keeping it under `<tag>-previous` makes recovery one line:
	 *   docker tag pstack:local-previous pstack:local && docker compose -p pstack-control … up -d
	 * Best-effort: on a host with no image yet there is nothing to keep.
	 */
	runner.Run("docker image tag "+swarm.Shq(tag)+" "+swarm.Shq(tag+"-previous")+" 2>/dev/null || true", exec.RunOptions{
		Label: "keep the previous " + tag,
	})

	// The Dockerfile is WRITTEN, never interpolated into a command: it is a multi-KB document full of
	// backticks and `$`, and passing it through a shell lets the shell read it. A build context is a
	// directory; give docker a directory.
	ctx, err := os.MkdirTemp("", "pstack-image-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(ctx)

	if !ui {
		b, err := os.ReadFile(binary)
		if err != nil {
			return fmt.Errorf("cannot read the pstack binary to copy into the image: %w", err)
		}
		if err := os.WriteFile(filepath.Join(ctx, "pstack"), b, 0o777); err != nil {
			return err
		}
	}
	if dist != "" {
		// ESCAPE HATCH: build the UI from local files, for a change that is not published yet.
		if !exists(filepath.Join(dist, "index.html")) {
			return fmt.Errorf("no built UI at %s — expected an index.html there", dist)
		}
		if err := os.CopyFS(filepath.Join(ctx, "dist"), os.DirFS(dist)); err != nil {
			return err
		}
		// The nginx config sits next to `dist/` in the package, not inside it.
		conf := filepath.Join(dist, "..", "nginx.conf")
		if !exists(conf) {
			return fmt.Errorf("found the UI assets at %s but no nginx.conf beside them — the package is "+
				"incomplete, so the image would serve the SPA with no /api proxy and no deep-link "+
				"fallback.", dist)
		}
		b, err := os.ReadFile(conf)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(ctx, "nginx.conf"), b, 0o666); err != nil {
			return err
		}
	}

	var df string
	switch {
	case dist != "":
		df = localUIDockerfile()
	case ui:
		df = UIDockerfile("")
	default:
		df = ControlDockerfile("")
	}
	if err := os.WriteFile(filepath.Join(ctx, "Dockerfile"), []byte(df), 0o666); err != nil {
		return err
	}

	switch {
	case dist != "":
		fmt.Fprintf(out, "building %s from %s\n", tag, dist)
	case ui:
		fmt.Fprintf(out, "building %s (pstack %s, from npm)\n", tag, version.Get())
	default:
		fmt.Fprintf(out, "building %s (pstack %s, from %s)\n", tag, version.Get(), binary)
	}
	// `--pull` so a months-old cached base does not silently pin an old runtime; the base layers
	// are shared with anything else on the box, so the cost is one manifest check.
	// JSON.stringify for the two args, as the TS did — not shq.
	r := runner.Run("docker build --pull -t "+string(jsonx.Must(tag))+" "+string(jsonx.Must(ctx)), exec.RunOptions{
		Label: "docker build " + tag,
	})
	if !r.OK {
		o := r.Stderr
		if o == "" {
			o = r.Stdout
		}
		return fmt.Errorf("docker build failed (exit %d).\n%s", r.Code, js.Truncate(strings.TrimSpace(o), 2000))
	}
	fmt.Fprintf(out, "built %s\n", tag)
	if ui {
		fmt.Fprintln(out, "  next:  pstack init --ui advanced --domain <preview.example.com> --acme-email <you@example.com>")
	} else {
		fmt.Fprintln(out, "  next:  pstack init --domain <preview.example.com> --acme-email <you@example.com>")
	}
	return nil
}

// exists is Bun.file(p).exists(): a regular file (or anything stat-able) at p.
func exists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
