package upgrade

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/samishal1998/preview-stacks/packages/pstack/internal/exec"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/initctl"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/spec"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/testfacts"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/version"
)

const defaultEnv = "DATA_DIR=/var/lib/pstack\nDOMAIN=preview.example.com\nPSTACK_UI_IMAGE=pstack-ui:local\nACME_EMAIL=ops@example.com\nDNS_PROVIDER=\nPSTACK_IMAGE=pstack:local\nPSTACK_TOKEN=the-existing-machine-token-0123456789"
const defaultCompose = "services:\n  traefik:\n    command:\n      - --certificatesresolvers.le.acme.httpchallenge=true\n  pstack:\n    image: x\n"
const dnsAdvCompose = "services:\n  traefik:\n    command:\n      - --certificatesresolvers.le.acme.dnschallenge=true\n  advanced-ui:\n    image: y\n"

// control is a control directory as a previous `init` would have left it. "" keeps the default.
func control(t *testing.T, env, compose string) (dataDir, dir string) {
	t.Helper()
	dataDir = t.TempDir()
	dir = filepath.Join(dataDir, "control")
	if err := os.MkdirAll(dir, 0o777); err != nil {
		t.Fatal(err)
	}
	if env == "" {
		env = defaultEnv
	}
	if compose == "" {
		compose = defaultCompose
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(env), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(compose), 0o644); err != nil {
		t.Fatal(err)
	}
	return dataDir, dir
}

// healthyRunner: every docker call succeeds AND reports `healthy`, so init writes its files and
// its final health wait settles immediately — without a daemon.
func healthyRunner() *exec.Fake { return exec.NewFake(nil, "healthy") }

// realControl is a control directory generated by the REAL `init`, with docker faked.
//
// This is the test that matters. The hand-written fixtures pin the parser's behaviour, but they are
// only as good as a guess about what `init` emits — and that guess was wrong: the UI detector looked
// for a service named `pstack-ui`, which exists in every generated file only as a Traefik ROUTER
// name. Every host read as `basic`, and `upgrade` removed the advanced UI it was meant to preserve,
// while a fabricated fixture said it worked.
func realControl(t *testing.T, ui initctl.UI, challenge initctl.Challenge) string {
	t.Helper()
	dataDir := t.TempDir()
	o := initctl.Options{
		DataDir: dataDir, Domain: "preview.example.com", AcmeEmail: "ops@example.com",
		Challenge: challenge, UI: ui, Orchestrator: spec.Compose, Runner: healthyRunner(), Out: &bytes.Buffer{},
	}
	if challenge == initctl.DNS01 {
		o.DNSProvider = "cloudflare"
	}
	if err := initctl.Init(o); err != nil {
		t.Fatal(err)
	}
	return dataDir
}

func cmds(steps []Step) []string {
	out := []string{}
	for _, s := range steps {
		out = append(out, s.Cmd)
	}
	return out
}

func find(steps []Step, prefix string) *Step {
	for i := range steps {
		if strings.HasPrefix(steps[i].Cmd, prefix) {
			return &steps[i]
		}
	}
	return nil
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

func quiet() exec.Runner { return exec.New(exec.Options{DryRun: true, Level: exec.Quiet}) }

func mustRead(t *testing.T, dataDir string) *ControlState {
	t.Helper()
	s, err := ReadControlState(dataDir)
	if err != nil {
		t.Fatal(err)
	}
	return s
}

func TestUpgrade(t *testing.T) {
	t.Setenv("PSTACK_TOKEN", "")
	os.Unsetenv("PSTACK_TOKEN")
	os.Unsetenv("PSTACK_IMAGE")
	os.Unsetenv("PSTACK_UI_IMAGE")
	LookPath = func() string { return "" }

	t.Run("detects the UI mode from a control file init actually generated", func(t *testing.T) {
		// negative control: anchor advancedSvc on `pstack-ui:` instead — reads basic, the plan lacks --ui.
		s := mustRead(t, realControl(t, initctl.Advanced, initctl.HTTP01))
		// The bug: this said `basic`, so the upgrade dropped the advanced UI container.
		if s.UI != initctl.Advanced {
			t.Fatalf("ui = %s", s.UI)
		}
		steps := PlanUpgrade(PlanArgs{Phase: Resume, Target: "x", State: s})
		if !contains(cmds(steps), "pstack build-image --ui") || !strings.Contains(find(steps, "pstack init").Cmd, "--ui advanced") {
			t.Errorf("plan: %v", cmds(steps))
		}

		s = mustRead(t, realControl(t, initctl.Basic, initctl.HTTP01))
		if s.UI != initctl.Basic {
			t.Fatalf("ui = %s", s.UI)
		}
		// …and a basic host does not build or wire an image it does not run.
		for _, c := range cmds(PlanUpgrade(PlanArgs{Phase: Resume, Target: "x", State: s})) {
			if strings.Contains(c, "--ui") {
				t.Errorf("basic host builds the UI: %s", c)
			}
		}
	})

	t.Run("detects the challenge mode from a control file init actually generated", func(t *testing.T) {
		// Same discipline for the other value that is not in `.env`. Getting this wrong is expensive in
		// a way a re-run cannot undo: every per-PR router would order its own certificate.
		// negative control: default Challenge to DNS01 and match `httpchallenge` — the http case reads dns01.
		if s := mustRead(t, realControl(t, initctl.Basic, initctl.DNS01)); s.Challenge != initctl.DNS01 {
			t.Errorf("challenge = %s", s.Challenge)
		}
		if s := mustRead(t, realControl(t, initctl.Advanced, initctl.HTTP01)); s.Challenge != initctl.HTTP01 {
			t.Errorf("challenge = %s", s.Challenge)
		}
	})

	t.Run("--ui overrides the detection, for a host a bad upgrade already flipped", func(t *testing.T) {
		// After the 0.25.1 bug the compose file genuinely says basic, so detection is truthful and
		// useless. This is how the host gets put back without hand-writing init's whole command line.
		// negative control: ignore opts.UI in Upgrade — the plan lacks --ui advanced.
		r, err := Upgrade(Options{DataDir: realControl(t, initctl.Basic, initctl.HTTP01), Phase: Resume, UI: initctl.Advanced, Runner: quiet(), Log: func(string) {}})
		if err != nil {
			t.Fatal(err)
		}
		if !contains(cmds(r.Steps), "pstack build-image --ui") || !strings.Contains(find(r.Steps, "pstack init").Cmd, "--ui advanced") {
			t.Errorf("plan: %v", cmds(r.Steps))
		}
	})

	t.Run("reads back what init decided, including the two facts that are not in .env", func(t *testing.T) {
		// negative control: read the challenge from .env (absent → http01) — the dns case fails.
		dataDir, _ := control(t, "", "")
		s := mustRead(t, dataDir)
		if s.Token != "the-existing-machine-token-0123456789" || s.Domain != "preview.example.com" || s.AcmeEmail != "ops@example.com" {
			t.Errorf("env fields: %+v", s)
		}
		// Neither of these is in `.env` — both are read back out of the GENERATED compose file.
		if s.Challenge != initctl.HTTP01 || s.UI != initctl.Basic {
			t.Errorf("compose facts: %+v", s)
		}

		dataDir, _ = control(t, "DOMAIN=preview.example.com\nACME_EMAIL=ops@example.com\nDNS_PROVIDER=cloudflare\nPSTACK_TOKEN=tok-abcdefghijklmnop", dnsAdvCompose)
		s = mustRead(t, dataDir)
		if s.Challenge != initctl.DNS01 || s.UI != initctl.Advanced || s.DNSProvider != "cloudflare" {
			t.Errorf("dns/advanced: %+v", s)
		}
	})

	t.Run("the token is carried into init — the trap this command exists to remove", func(t *testing.T) {
		// negative control: drop PSTACK_TOKEN from initEnv — the env assertion fails.
		dataDir, _ := control(t, "", "")
		steps := PlanUpgrade(PlanArgs{Phase: Resume, Target: "0.25.1", State: mustRead(t, dataDir), BinPath: "/usr/local/bin/pstack"})
		init := find(steps, "pstack init")
		/*
		 * Without this, `init` generates a fresh PSTACK_TOKEN and every CI job holding the old one
		 * starts getting 401s — from a command whose entire purpose was "change nothing but the
		 * version". This assertion is the reason `upgrade` exists at all.
		 */
		if init == nil || init.Env["PSTACK_TOKEN"] != "the-existing-machine-token-0123456789" {
			t.Fatalf("init step: %+v", init)
		}
		// …and it carries settings an operator would otherwise have to remember exactly.
		for _, want := range []string{"--domain 'preview.example.com'", "--acme-email 'ops@example.com'", "--challenge http01"} {
			if !strings.Contains(init.Cmd, want) {
				t.Errorf("missing %q in %s", want, init.Cmd)
			}
		}
		// A basic-UI host does not build the SPA image it does not run.
		for _, c := range cmds(steps) {
			if strings.Contains(c, "--ui") {
				t.Errorf("builds the UI: %s", c)
			}
		}
	})

	t.Run("an advanced-UI, dns01 host rebuilds both images and keeps its challenge mode", func(t *testing.T) {
		// negative control: drop `--dns-provider` from initFlags — the exact command differs.
		dataDir, _ := control(t, "DOMAIN=p.example.com\nACME_EMAIL=o@example.com\nDNS_PROVIDER=cloudflare\nPSTACK_TOKEN=tok-abcdefghijklmnop", dnsAdvCompose)
		got := cmds(PlanUpgrade(PlanArgs{Phase: Resume, Target: "latest", State: mustRead(t, dataDir), BinPath: "/usr/local/bin/pstack"}))
		want := []string{
			"pstack build-image",
			"pstack build-image --ui",
			"pstack init --domain 'p.example.com' --acme-email 'o@example.com' --challenge dns01 --dns-provider 'cloudflare' --ui advanced --orchestrator compose",
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("got %v\nwant %v", got, want)
		}
	})

	t.Run("the install phase installs into the directory this binary actually lives in", func(t *testing.T) {
		// A user-prefix install (~/.local/bin) upgraded into the installer's default (/usr/local/bin)
		// would leave two binaries with the old one first on PATH — an upgrade that reports success
		// and changes nothing.
		// negative control: return "" from InstallDirFor — PSTACK_INSTALL_DIR disappears from the command.
		for in, want := range map[string]string{
			"/usr/local/bin/pstack":          "/usr/local/bin",
			"/home/deploy/.local/bin/pstack": "/home/deploy/.local/bin",
			"":                               "",
		} {
			if got := InstallDirFor(in); got != want {
				t.Errorf("InstallDirFor(%q) = %q, want %q", in, got, want)
			}
		}
		if got := InstallCommand("0.29.1", "/usr/local/bin"); got != "curl -fsSL https://github.com/samishal1998/preview-stacks/releases/download/v0.29.1/install.sh | PSTACK_VERSION='0.29.1' PSTACK_INSTALL_DIR='/usr/local/bin' sh" {
			t.Errorf("pinned: %s", got)
		}
		if got := InstallCommand("latest", ""); got != "curl -fsSL https://github.com/samishal1998/preview-stacks/releases/latest/download/install.sh | sh" {
			t.Errorf("latest: %s", got)
		}

		dataDir, _ := control(t, "", "")
		steps := PlanUpgrade(PlanArgs{Phase: Install, Target: "0.29.1", State: mustRead(t, dataDir), BinPath: "/usr/local/bin/pstack"})
		if steps[0].Cmd != InstallCommand("0.29.1", "/usr/local/bin") || steps[0].Env != nil {
			t.Errorf("install step: %+v", steps[0])
		}
		/*
		 * The handoff, and it is load-bearing: `build-image` copies the RUNNING binary into the image,
		 * so a single process would install 0.29.1 and then faithfully build a 0.29.0 image. The second
		 * phase has to be a new process running the new code.
		 */
		if steps[1].Cmd != "pstack upgrade --resume" {
			t.Errorf("handoff: %+v", steps[1])
		}
	})

	t.Run("the DNS-01 credential is read back and carried into init — the other thing that must not rotate", func(t *testing.T) {
		// `init` rewrites control/dns.env from PSTACK_DNS_TOKEN on EVERY run. An upgrade that does not
		// hand it over blanks the only copy: Traefik is recreated with no credential, the wildcard
		// already in the volume keeps serving, and the renewal silently fails weeks later.
		// negative control: drop `PSTACK_DNS_TOKEN` from initEnv() — the env assertion fails.
		dataDir := t.TempDir()
		if err := initctl.Init(initctl.Options{
			DataDir: dataDir, Domain: "preview.example.com", AcmeEmail: "ops@example.com",
			Challenge: initctl.DNS01, DNSProvider: "cloudflare", Token: "cf-token-0123456789abcdef",
			UI: initctl.Basic, Orchestrator: spec.Compose, Runner: healthyRunner(), Out: &bytes.Buffer{},
		}); err != nil {
			t.Fatal(err)
		}
		state := mustRead(t, dataDir)
		if state.DNSProvider != "cloudflare" || state.DNSToken != "cf-token-0123456789abcdef" {
			t.Fatalf("state: %+v", state)
		}
		adv := *state
		adv.UI = initctl.Advanced
		for _, steps := range [][]Step{PlanUpgrade(PlanArgs{Phase: Resume, Target: "x", State: state}), PlanUISwitch(&adv)} {
			initStep := find(steps, "pstack init")
			if initStep.Env["PSTACK_TOKEN"] != state.Token || initStep.Env["PSTACK_DNS_TOKEN"] != "cf-token-0123456789abcdef" {
				t.Errorf("init env: %v", initStep.Env)
			}
		}
		// The dry-run transcript says so, because that is what an operator checks before trusting it.
		var said []string
		if _, err := Upgrade(Options{DataDir: dataDir, Target: "0.28.0", Runner: quiet(), Log: func(l string) { said = append(said, l) }}); err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(strings.Join(said, "\n"), "(with the existing PSTACK_TOKEN and PSTACK_DNS_TOKEN)") {
			t.Errorf("transcript:\n%s", strings.Join(said, "\n"))
		}

		// An http01 host has a dns.env with no token line at all — nothing is carried, and nothing breaks.
		httpDir, _ := control(t, "", "")
		state = mustRead(t, httpDir)
		if state.DNSToken != "" {
			t.Errorf("dnsToken = %q", state.DNSToken)
		}
		initStep := find(PlanUpgrade(PlanArgs{Phase: Resume, Target: "x", State: state}), "pstack init")
		if !reflect.DeepEqual(initStep.Env, map[string]string{"PSTACK_TOKEN": state.Token}) {
			t.Errorf("env = %v", initStep.Env)
		}
	})

	t.Run("a Go-release target is simply installed — this binary IS the Go release", func(t *testing.T) {
		// The 0.28.0 bridge refused a >= 0.29.0 target with the one-time hop; the hop lands on
		// `--resume` of this binary, and from here every target is the installer's to fetch.
		// negative control: put the hop refusal back — the plan below has no install step.
		dataDir, _ := control(t, "", "")
		r, err := Upgrade(Options{DataDir: dataDir, Target: "0.30.0", Runner: quiet(), Log: func(string) {}})
		if err != nil || !strings.Contains(cmds(r.Steps)[0], "releases/download/v0.30.0/install.sh") {
			t.Fatalf("got %v %v", r, err)
		}
		r, err = Upgrade(Options{DataDir: dataDir, Phase: Resume, Target: "0.30.0", Runner: quiet(), Log: func(string) {}})
		if err != nil || cmds(r.Steps)[0] != "pstack build-image" {
			t.Errorf("resume: %v %v", r, err)
		}
	})

	t.Run("a host with no control stack is refused by name, not by a stack trace", func(t *testing.T) {
		// negative control: return an empty ControlState for a missing .env — no error.
		empty := t.TempDir()
		_, err := ReadControlState(empty)
		if err == nil || !strings.Contains(err.Error(), "no control stack found") {
			t.Errorf("got %v", err)
		}
		if want := goldenStderr(t, "upgrade-no-control"); "pstack: "+strings.ReplaceAll(err.Error(), empty, "<DATA>")+"\n" != want {
			t.Errorf("message differs\n--- got\n%s\n--- want\n%s", err.Error(), want)
		}

		// A .env that predates a field, or was hand-edited, names the missing key and the fix.
		partial, _ := control(t, "DOMAIN=x.example.com\nACME_EMAIL=o@example.com", "")
		if _, err := ReadControlState(partial); err == nil || !strings.Contains(err.Error(), "PSTACK_TOKEN") {
			t.Errorf("got %v", err)
		}

		// No compose file ⇒ the challenge cannot be read back. Refused rather than defaulted:
		// defaulting to http01 on a dns01 host makes every PR order its own certificate.
		noCompose, dir := control(t, "", "")
		if err := os.Remove(filepath.Join(dir, "docker-compose.yml")); err != nil {
			t.Fatal(err)
		}
		if _, err := ReadControlState(noCompose); err == nil || !strings.Contains(err.Error(), "challenge mode cannot be read back") {
			t.Errorf("got %v", err)
		}
	})

	t.Run("--dry-run walks the plan without executing anything", func(t *testing.T) {
		// negative control: run the steps through a non-dry runner — `pstack build-image` is spawned and fails.
		dataDir, _ := control(t, "", "")
		var said []string
		r, err := Upgrade(Options{DataDir: dataDir, Target: "0.25.1", Phase: Resume, Runner: quiet(), Log: func(l string) { said = append(said, l) }})
		if err != nil {
			t.Fatal(err)
		}
		if len(r.Steps) != 2 { // basic UI: build + init
			t.Errorf("steps: %v", cmds(r.Steps))
		}
		if !strings.Contains(strings.Join(said, "\n"), "rebuilding and recreating") {
			t.Errorf("said %v", said)
		}
	})

	t.Run("a failed step names itself, the last lines, and what is left to run by hand", func(t *testing.T) {
		// negative control: drop the remaining-commands list from the error — the `(none)`/init line check fails.
		dataDir, _ := control(t, "", "")
		f := exec.NewFake(func(cmd string) bool { return cmd == "pstack build-image" }, "")
		f.Answer = func(cmd string) (exec.Result, bool) {
			if cmd == "pstack build-image" {
				return exec.Result{OK: false, Code: 1, Stderr: "l1\nl2\nl3\nl4\nl5\nl6\nl7\nl8\nl9\n"}, true
			}
			return exec.Result{}, false
		}
		_, err := Upgrade(Options{DataDir: dataDir, Phase: Resume, Runner: f, Log: func(string) {}})
		want := "build the control image failed (exit 1).\nl2\nl3\nl4\nl5\nl6\nl7\nl8\nl9\n\n" +
			"Nothing after this step ran. The remaining steps are ordinary commands you can run by hand:\n" +
			"  pstack init --domain 'preview.example.com' --acme-email 'ops@example.com' --challenge http01 --orchestrator compose"
		if err == nil || err.Error() != want {
			t.Errorf("got:\n%v\nwant:\n%s", err, want)
		}
	})
}

func TestUISwitch(t *testing.T) {
	os.Unsetenv("PSTACK_TOKEN")
	os.Unsetenv("PSTACK_IMAGE")
	os.Unsetenv("PSTACK_UI_IMAGE")

	t.Run("basic → advanced builds the SPA image and re-inits with the stored token", func(t *testing.T) {
		// negative control: use PlanUpgrade's resume list in SwitchUI — `pstack build-image` appears.
		var said []string
		changed, steps, err := SwitchUI(SwitchUIOptions{DataDir: realControl(t, initctl.Basic, initctl.HTTP01), UI: initctl.Advanced, Runner: quiet(), Log: func(l string) { said = append(said, l) }})
		if err != nil {
			t.Fatal(err)
		}
		if !changed {
			t.Error("not changed")
		}
		want := []string{
			"pstack build-image --ui",
			"pstack init --domain 'preview.example.com' --acme-email 'ops@example.com' --challenge http01 --ui advanced --orchestrator compose",
		}
		if !reflect.DeepEqual(cmds(steps), want) {
			t.Errorf("got %v", cmds(steps))
		}
		// The token again — the one thing you cannot get wrong without breaking every CI job.
		if find(steps, "pstack init").Env["PSTACK_TOKEN"] == "" {
			t.Error("no token")
		}
		if !strings.Contains(strings.Join(said, "\n"), "basic UI → advanced UI") {
			t.Errorf("said %v", said)
		}
	})

	t.Run("advanced → basic builds nothing — the API already carries the embedded UI", func(t *testing.T) {
		// negative control: build the UI image for basic too — the list has two entries.
		_, steps, err := SwitchUI(SwitchUIOptions{DataDir: realControl(t, initctl.Advanced, initctl.HTTP01), UI: initctl.Basic, Runner: quiet(), Log: func(string) {}})
		if err != nil {
			t.Fatal(err)
		}
		want := []string{"pstack init --domain 'preview.example.com' --acme-email 'ops@example.com' --challenge http01 --orchestrator compose"}
		if !reflect.DeepEqual(cmds(steps), want) {
			t.Errorf("got %v", cmds(steps))
		}
	})

	t.Run("switching to the mode already in use recreates nothing", func(t *testing.T) {
		// Recreating the control stack is a brief outage. "Already advanced" is an answer, not a reason
		// to cause one.
		// negative control: drop the `current.UI == opts.UI` early return — changed is true.
		var said []string
		changed, steps, err := SwitchUI(SwitchUIOptions{DataDir: realControl(t, initctl.Advanced, initctl.HTTP01), UI: initctl.Advanced, Runner: quiet(), Log: func(l string) { said = append(said, l) }})
		if err != nil {
			t.Fatal(err)
		}
		if changed || len(steps) != 0 || steps == nil {
			t.Errorf("changed=%v steps=%v", changed, steps)
		}
		if !strings.Contains(strings.Join(said, "\n"), "Already serving the advanced UI") {
			t.Errorf("said %v", said)
		}
	})
}

func goldenCLI(t *testing.T, name string) (stdout, stderr string) {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(testfacts.Golden(t), "cli", name+".json"))
	if err != nil {
		t.Fatal(err)
	}
	var g struct{ Stdout, Stderr string }
	if err := json.Unmarshal(b, &g); err != nil {
		t.Fatal(err)
	}
	return g.Stdout, g.Stderr
}

func goldenStderr(t *testing.T, name string) string {
	_, e := goldenCLI(t, name)
	return e
}

// The conformance transcripts for `upgrade -n --to 0.29.1` and `ui <other> -n` over each init cell:
// the runner's `[dry-run]` lines and Upgrade's own, interleaved on one writer. The CLI appends a
// trailing "Dry run — …" paragraph after Upgrade returns; that is cli's, not ours.
func TestUpgradeGoldens(t *testing.T) {
	t.Setenv("PSTACK_TOKEN", "golden-token-0123456789abcdef0123456789abcdef")
	os.Unsetenv("PSTACK_IMAGE")
	os.Unsetenv("PSTACK_UI_IMAGE")
	LookPath = func() string { return "/usr/local/bin/pstack" }

	for _, challenge := range []initctl.Challenge{initctl.HTTP01, initctl.DNS01} {
		for _, ui := range []initctl.UI{initctl.Basic, initctl.Advanced} {
			for _, orch := range []spec.Orchestrator{spec.Compose, spec.Swarm} {
				name := string(challenge) + "-" + string(ui) + "-" + string(orch)
				dataDir := t.TempDir()
				o := initctl.Options{
					DataDir: dataDir, Domain: "preview.example.com", AcmeEmail: "ops@example.com",
					Challenge: challenge, UI: ui, Orchestrator: orch, Runner: healthyRunner(), Out: &bytes.Buffer{},
				}
				if challenge == initctl.DNS01 {
					o.DNSProvider, o.Token = "cloudflare", "golden-dns-token-0123456789"
				}
				if err := initctl.Init(o); err != nil {
					t.Fatal(err)
				}

				t.Run("upgrade-plan-"+name, func(t *testing.T) {
					// negative control: print the resume plan before the install steps — the line order differs.
					var out bytes.Buffer
					runner := exec.New(exec.Options{DryRun: true, Out: &out})
					if _, err := Upgrade(Options{DataDir: dataDir, Target: "0.29.1", Runner: runner, Log: func(l string) { out.WriteString(l + "\n") }}); err != nil {
						t.Fatal(err)
					}
					want, _ := goldenCLI(t, "upgrade-plan-"+name)
					want = strings.TrimSuffix(want, "\n  Dry run — nothing was installed, built or recreated.\n")
					got := strings.ReplaceAll(out.String(), version.Get(), "<VERSION>")
					if got != want {
						t.Errorf("transcript differs\n--- got\n%s\n--- want\n%s", got, want)
					}
				})

				t.Run("ui-switch-dry-"+name, func(t *testing.T) {
					// negative control: say `→` without the domain suffix — the first line differs.
					other := initctl.Advanced
					if ui == initctl.Advanced {
						other = initctl.Basic
					}
					var out bytes.Buffer
					runner := exec.New(exec.Options{DryRun: true, Out: &out})
					if _, _, err := SwitchUI(SwitchUIOptions{DataDir: dataDir, UI: other, Runner: runner, Log: func(l string) { out.WriteString(l + "\n") }}); err != nil {
						t.Fatal(err)
					}
					want, _ := goldenCLI(t, "ui-switch-dry-"+name)
					if out.String() != want {
						t.Errorf("transcript differs\n--- got\n%s\n--- want\n%s", out.String(), want)
					}
				})
			}
		}
	}
}
