/**
 * The matrix: the reference's file → the Go package → which conformance files grade it → how they
 * stand. Reads the last junit run in .status/go.xml (`bun run ratchet` writes it), or pass --run.
 *
 *   bun scripts/status.ts [--run] [--write docs/port-status.md]
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PKG, parseJunit, runJunit, type Case } from './junit.ts';

type Row = { ts: string; go: string; group: string; tests?: string[] };
const rows = JSON.parse(readFileSync(join(PKG, 'port-map.json'), 'utf8')) as Row[];

const load = async (impl: 'go'): Promise<Case[] | null> => {
  if (process.argv.includes('--run')) return (await runJunit(impl)).cases;
  const p = join(PKG, '.status', `${impl}.xml`);
  return existsSync(p) ? parseJunit(readFileSync(p, 'utf8')) : null;
};
const go = await load('go');
const tally = (cases: Case[] | null, files: string[]) => {
  if (!cases) return '—';
  const mine = cases.filter((c) => files.includes(c.file) && c.verdict !== 'skip');
  return `${mine.filter((c) => c.verdict === 'pass').length}/${mine.length}`;
};

const lines = ['| group | reference → Go | conformance files | go |', '|---|---|---|---|'];
for (const r of rows) {
  const files = r.tests ?? [];
  lines.push(`| ${r.group} | \`${r.ts}\` → \`${r.go}\` | ${files.map((f) => f.replace('test/', '')).join(', ') || '—'} | ${tally(go, files)} |`);
}
const allFiles = [...new Set(rows.flatMap((r) => r.tests ?? []))];
lines.push(`| **all** | | | **${tally(go, allFiles)}** |`);
const md = lines.join('\n');
console.log(md);
const w = process.argv.indexOf('--write');
if (w >= 0 && process.argv[w + 1]) {
  writeFileSync(process.argv[w + 1]!, `# Port status\n\nGenerated by \`bun run status\` in packages/conformance.\n\n${md}\n`);
}
