// Code generated by oascmd-gen. DO NOT EDIT.

package apicli

import (
	"net/url"
	"os"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/samishal1998/openapi-commands"
)

// NewCommandTree returns the full generated command tree: group commands
// with every operation command attached. Attach the result onto your root
// command, or use the per-operation constructors directly.
func NewCommandTree(exec oascmd.ExecOptions) []*cobra.Command {
	root := &cobra.Command{}
	groups := map[string]*cobra.Command{"": root}
	group := func(path ...string) *cobra.Command {
		key := ""
		cmd := root
		for _, word := range path {
			key += "/" + word
			child, ok := groups[key]
			if !ok {
				child = &cobra.Command{Use: word}
				cmd.AddCommand(child)
				groups[key] = child
			}
			cmd = child
		}
		return cmd
	}
	group("users").AddCommand(NewUsersMeCommand(exec))
	group("config").AddCommand(NewConfigExportCommand(exec))
	group("config").AddCommand(NewConfigImportCommand(exec))
	group("config").AddCommand(NewConfigImportSealedCommand(exec))
	group("host").AddCommand(NewHostControlCommand(exec))
	group("deployments").AddCommand(NewDeploymentsListCommand(exec))
	group("deployments").AddCommand(NewDeploymentsDeleteCommand(exec))
	group("deployments").AddCommand(NewDeploymentsGetCommand(exec))
	group("deployments").AddCommand(NewDeploymentsPutCommand(exec))
	group("deployments").AddCommand(NewDeploymentsCancelCommand(exec))
	group("deployments", "containers").AddCommand(NewDeploymentsContainersActCommand(exec))
	group("deployments").AddCommand(NewDeploymentsDownCommand(exec))
	group("deployments", "logs").AddCommand(NewDeploymentsLogsGetCommand(exec))
	group("deployments", "readiness").AddCommand(NewDeploymentsReadinessGetCommand(exec))
	group("deployments", "runtime").AddCommand(NewDeploymentsRuntimeGetCommand(exec))
	group("deployments", "share").AddCommand(NewDeploymentsShareCreateCommand(exec))
	group("deployments").AddCommand(NewDeploymentsSleepCommand(exec))
	group("deployments", "source").AddCommand(NewDeploymentsSourceGetCommand(exec))
	group("deployments").AddCommand(NewDeploymentsUpCommand(exec))
	group("deployments").AddCommand(NewDeploymentsVerifyCommand(exec))
	group("deployments").AddCommand(NewDeploymentsWakeCommand(exec))
	group("host").AddCommand(NewHostHealthCommand(exec))
	group("host-vars").AddCommand(NewHostVarsListCommand(exec))
	group("host-vars").AddCommand(NewHostVarsDeleteCommand(exec))
	group("host-vars").AddCommand(NewHostVarsPutCommand(exec))
	group("jobs").AddCommand(NewJobsListCommand(exec))
	group("jobs").AddCommand(NewJobsGetCommand(exec))
	group("jobs").AddCommand(NewJobsCancelCommand(exec))
	group("notifiers").AddCommand(NewNotifiersListCommand(exec))
	group("notifiers").AddCommand(NewNotifiersCreateCommand(exec))
	group("notifiers").AddCommand(NewNotifiersMetaCommand(exec))
	group("notifiers").AddCommand(NewNotifiersDeleteCommand(exec))
	group("notifiers").AddCommand(NewNotifiersGetCommand(exec))
	group("notifiers").AddCommand(NewNotifiersUpdateCommand(exec))
	group("notifiers", "deliveries").AddCommand(NewNotifiersDeliveriesListCommand(exec))
	group("notifiers", "deliveries").AddCommand(NewNotifiersDeliveriesRedeliverCommand(exec))
	group("notifiers").AddCommand(NewNotifiersTestCommand(exec))
	group("host").AddCommand(NewHostProbeCommand(exec))
	group("registries").AddCommand(NewRegistriesListCommand(exec))
	group("registries").AddCommand(NewRegistriesDeleteCommand(exec))
	group("registries").AddCommand(NewRegistriesPutCommand(exec))
	group("routing").AddCommand(NewRoutingListCommand(exec))
	group("routing").AddCommand(NewRoutingLiveCommand(exec))
	group("routing").AddCommand(NewRoutingDeleteCommand(exec))
	group("routing").AddCommand(NewRoutingGetCommand(exec))
	group("routing").AddCommand(NewRoutingPutCommand(exec))
	group("settings").AddCommand(NewSettingsListCommand(exec))
	group("settings").AddCommand(NewSettingsSetDefaultRoleCommand(exec))
	group("settings").AddCommand(NewSettingsSetMaxJobsCommand(exec))
	group("specs").AddCommand(NewSpecsListCommand(exec))
	group("specs").AddCommand(NewSpecsDeleteCommand(exec))
	group("specs").AddCommand(NewSpecsGetCommand(exec))
	group("specs").AddCommand(NewSpecsPutCommand(exec))
	group("sso", "config").AddCommand(NewSsoConfigDeleteCommand(exec))
	group("sso", "config").AddCommand(NewSsoConfigGetCommand(exec))
	group("sso", "config").AddCommand(NewSsoConfigPutCommand(exec))
	group("sso", "provider").AddCommand(NewSsoProviderDeleteCommand(exec))
	group("sso", "provider").AddCommand(NewSsoProviderPutCommand(exec))
	group("swarm").AddCommand(NewSwarmGetCommand(exec))
	group("swarm").AddCommand(NewSwarmJoinCommand(exec))
	group("host").AddCommand(NewHostTerminalSessionsCommand(exec))
	group("tokens").AddCommand(NewTokensListCommand(exec))
	group("tokens").AddCommand(NewTokensCreateCommand(exec))
	group("tokens").AddCommand(NewTokensDeleteCommand(exec))
	group("users").AddCommand(NewUsersListCommand(exec))
	group("users").AddCommand(NewUsersCreateCommand(exec))
	group("users").AddCommand(NewUsersDeleteCommand(exec))
	group("users").AddCommand(NewUsersSetRoleCommand(exec))
	group("users", "password").AddCommand(NewUsersPasswordSetCommand(exec))
	return root.Commands()
}

// NewUsersMeCommand returns the "users me" command (GET /api/auth/me).
func NewUsersMeCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "me",
		Short: "Who this credential is, and at what role.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/auth/me",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewConfigExportCommand returns the "config export" command (GET
// /api/config).
func NewConfigExportCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "export",
		Short: "THE WHOLE PORTABLE CONFIGURATION IN PLAINTEXT: password hashes, token hashes, host secrets. Root token only, and it emits an event.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/config",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewConfigImportCommand returns the "config import" command (POST
// /api/config).
func NewConfigImportCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "import",
		Short: "Apply such a document, create-or-skip. It can add but never repoint.",
	}
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "POST",
			Path:   "/api/config",
		}
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewConfigImportSealedCommand returns the "config import-sealed" command
// (POST /api/config/sealed).
func NewConfigImportSealedCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "import-sealed",
		Short: "Apply a sealed export, unsealed with a passphrase. Admin only.",
	}
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "POST",
			Path:   "/api/config/sealed",
		}
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostControlCommand returns the "host control" command (GET
// /api/control).
func NewHostControlCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "control",
		Short: "The control stack's own containers. Read-only, never actionable.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/control",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsListCommand returns the "deployments list" command (GET
// /api/deployments).
func NewDeploymentsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Every deployment, with its busy/running state.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/deployments",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsDeleteCommand returns the "deployments delete" command
// (DELETE /api/deployments/{id}).
func NewDeploymentsDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Forget a deployment. Refused while its containers exist.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/deployments/{id}",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsGetCommand returns the "deployments get" command (GET
// /api/deployments/{id}).
func NewDeploymentsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "One deployment's meta and spec summary.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/deployments/{id}",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsPutCommand returns the "deployments put" command (PUT
// /api/deployments/{id}).
func NewDeploymentsPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID   string
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "Submit or replace a deployment. The spec is parsed before it is stored.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/deployments/{id}",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsCancelCommand returns the "deployments cancel" command
// (POST /api/deployments/{id}/cancel).
func NewDeploymentsCancelCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "cancel",
		Short: "Stop everything this stack has outstanding — running and queued.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/cancel",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsContainersActCommand returns the "deployments containers
// act" command (POST /api/deployments/{id}/containers/{name}/{action}).
func NewDeploymentsContainersActCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID     string
		flagName   string
		flagAction string
	)
	cmd := &cobra.Command{
		Use:   "act",
		Short: "Start, stop or restart one container.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().StringVar(&flagName, "name", "", "The container's name")
	cmd.Flags().StringVar(&flagAction, "action", "", "(one of: start, stop, restart)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	_ = cmd.MarkFlagRequired("name")
	_ = cmd.MarkFlagRequired("action")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("action") {
			if err := oascmd.ValidateEnum("action", []string{"start", "stop", "restart"}, flagAction); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/containers/{name}/{action}",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		req.PathParams["name"] = flagName
		req.PathParams["action"] = flagAction
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsDownCommand returns the "deployments down" command (POST
// /api/deployments/{id}/down).
func NewDeploymentsDownCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID     string
		bodyVerify bool
		bodyForce  bool
		flagData   string
	)
	cmd := &cobra.Command{
		Use:   "down",
		Short: "Tear down. Preempts whatever the stack is doing.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().BoolVar(&bodyVerify, "verify", true, "Run the leak check afterwards.")
	cmd.Flags().BoolVar(&bodyForce, "force", false, "Required to tear down a `kind: shared` deployment.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/down",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		body := map[string]any{}
		if cmd.Flags().Changed("verify") {
			body["verify"] = bodyVerify
		}
		if cmd.Flags().Changed("force") {
			body["force"] = bodyForce
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsLogsGetCommand returns the "deployments logs get" command
// (GET /api/deployments/{id}/logs).
func NewDeploymentsLogsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagTail    int64
		flagService string
		flagID      string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "A slice of container logs, redacted.",
	}
	cmd.Flags().Int64Var(&flagTail, "tail", 0, "How many lines.")
	cmd.Flags().StringVar(&flagService, "service", "", "One service instead of all.")
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/deployments/{id}/logs",
			PathParams: map[string]string{},
			Query:      url.Values{},
		}
		if cmd.Flags().Changed("tail") {
			req.Query.Set("tail", strconv.FormatInt(flagTail, 10))
		}
		if cmd.Flags().Changed("service") {
			req.Query.Set("service", flagService)
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsReadinessGetCommand returns the "deployments readiness
// get" command (GET /api/deployments/{id}/readiness).
func NewDeploymentsReadinessGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagTimeout int64
		flagID      string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "The readiness verdict, optionally waiting for one.",
	}
	cmd.Flags().Int64Var(&flagTimeout, "timeout", 0, "Milliseconds to wait for a verdict.")
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/deployments/{id}/readiness",
			PathParams: map[string]string{},
			Query:      url.Values{},
		}
		if cmd.Flags().Changed("timeout") {
			req.Query.Set("timeout", strconv.FormatInt(flagTimeout, 10))
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsRuntimeGetCommand returns the "deployments runtime get"
// command (GET /api/deployments/{id}/runtime).
func NewDeploymentsRuntimeGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Containers, routes, findings and the host's ACME challenge mode.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/deployments/{id}/runtime",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsShareCreateCommand returns the "deployments share create"
// command (POST /api/deployments/{id}/share).
func NewDeploymentsShareCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID    string
		bodyViews []string
		bodyTTL   string
		flagData  string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Mint a read-only link to one deployment.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().StringSliceVar(&bodyViews, "views", nil, "What the link may open. (one of: details, logs)")
	cmd.Flags().StringVar(&bodyTTL, "ttl", "", "How long it lives, e.g. `7d`.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("views") {
			if err := oascmd.ValidateEnum("views", []string{"details", "logs"}, bodyViews...); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/share",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		body := map[string]any{}
		if cmd.Flags().Changed("views") {
			body["views"] = bodyViews
		}
		if cmd.Flags().Changed("ttl") {
			body["ttl"] = bodyTTL
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsSleepCommand returns the "deployments sleep" command
// (POST /api/deployments/{id}/sleep).
func NewDeploymentsSleepCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "sleep",
		Short: "Take the project down, keeping every volume and axis.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/sleep",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsSourceGetCommand returns the "deployments source get"
// command (GET /api/deployments/{id}/source).
func NewDeploymentsSourceGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "The stored spec and compose file, as submitted.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/deployments/{id}/source",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsUpCommand returns the "deployments up" command (POST
// /api/deployments/{id}/up).
func NewDeploymentsUpCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "up",
		Short: "Deploy. 202 with a job — queued when the stack is busy.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/up",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsVerifyCommand returns the "deployments verify" command
// (POST /api/deployments/{id}/verify).
func NewDeploymentsVerifyCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "verify",
		Short: "Run every assert_gone and report what survived.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/verify",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewDeploymentsWakeCommand returns the "deployments wake" command (POST
// /api/deployments/{id}/wake).
func NewDeploymentsWakeCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagID string
	)
	cmd := &cobra.Command{
		Use:   "wake",
		Short: "Bring a sleeping deployment back.",
	}
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/deployments/{id}/wake",
			PathParams: map[string]string{},
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostHealthCommand returns the "host health" command (GET
// /api/health).
func NewHostHealthCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "health",
		Short: "Liveness, whether auth is enforced, whether any account exists, and the version. No token needed.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/health",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostVarsListCommand returns the "host-vars list" command (GET
// /api/host-vars).
func NewHostVarsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Every host variable. A secret's NAME, never its value.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/host-vars",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostVarsDeleteCommand returns the "host-vars delete" command (DELETE
// /api/host-vars/{name}).
func NewHostVarsDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagName string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/host-vars/{name}",
	}
	cmd.Flags().StringVar(&flagName, "name", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("name")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/host-vars/{name}",
			PathParams: map[string]string{},
		}
		req.PathParams["name"] = flagName
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostVarsPutCommand returns the "host-vars put" command (PUT
// /api/host-vars/{name}).
func NewHostVarsPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagName   string
		bodyValue  string
		bodySecret bool
		flagData   string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "PUT /api/host-vars/{name}",
	}
	cmd.Flags().StringVar(&flagName, "name", "", "")
	cmd.Flags().StringVar(&bodyValue, "value", "", "")
	cmd.Flags().BoolVar(&bodySecret, "secret", false, "A secret's value is never returned by any route again.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("name")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/host-vars/{name}",
			PathParams: map[string]string{},
		}
		req.PathParams["name"] = flagName
		body := map[string]any{}
		if cmd.Flags().Changed("value") {
			body["value"] = bodyValue
		}
		if cmd.Flags().Changed("secret") {
			body["secret"] = bodySecret
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewJobsListCommand returns the "jobs list" command (GET /api/jobs).
func NewJobsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "The last 50 jobs, newest first. In memory — a restart loses them.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/jobs",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewJobsGetCommand returns the "jobs get" command (GET
// /api/jobs/{jobId}).
func NewJobsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagJobID string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "One job — state, transcript and outcome.",
	}
	cmd.Flags().StringVar(&flagJobID, "job-id", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("job-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/jobs/{jobId}",
			PathParams: map[string]string{},
		}
		req.PathParams["jobId"] = flagJobID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewJobsCancelCommand returns the "jobs cancel" command (POST
// /api/jobs/{jobId}/cancel).
func NewJobsCancelCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagJobID string
	)
	cmd := &cobra.Command{
		Use:   "cancel",
		Short: "Stop one running job. Partial state is left as it is.",
	}
	cmd.Flags().StringVar(&flagJobID, "job-id", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("job-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/jobs/{jobId}/cancel",
			PathParams: map[string]string{},
		}
		req.PathParams["jobId"] = flagJobID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersListCommand returns the "notifiers list" command (GET
// /api/notifiers).
func NewNotifiersListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "GET /api/notifiers",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/notifiers",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersCreateCommand returns the "notifiers create" command (POST
// /api/notifiers).
func NewNotifiersCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "POST /api/notifiers",
	}
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "POST",
			Path:   "/api/notifiers",
		}
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersMetaCommand returns the "notifiers meta" command (GET
// /api/notifiers/meta).
func NewNotifiersMetaCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "meta",
		Short: "Every event name a notifier may subscribe to, and each type's config shape.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/notifiers/meta",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersDeleteCommand returns the "notifiers delete" command
// (DELETE /api/notifiers/{notifierId}).
func NewNotifiersDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/notifiers/{notifierId}",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/notifiers/{notifierId}",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersGetCommand returns the "notifiers get" command (GET
// /api/notifiers/{notifierId}).
func NewNotifiersGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "GET /api/notifiers/{notifierId}",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/notifiers/{notifierId}",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersUpdateCommand returns the "notifiers update" command (PATCH
// /api/notifiers/{notifierId}).
func NewNotifiersUpdateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
		flagData       string
	)
	cmd := &cobra.Command{
		Use:   "update",
		Short: "PATCH /api/notifiers/{notifierId}",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PATCH",
			Path:       "/api/notifiers/{notifierId}",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersDeliveriesListCommand returns the "notifiers deliveries
// list" command (GET /api/notifiers/{notifierId}/deliveries).
func NewNotifiersDeliveriesListCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "GET /api/notifiers/{notifierId}/deliveries",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/notifiers/{notifierId}/deliveries",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersDeliveriesRedeliverCommand returns the "notifiers
// deliveries redeliver" command (POST
// /api/notifiers/{notifierId}/deliveries/{deliveryId}/redeliver).
func NewNotifiersDeliveriesRedeliverCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
		flagDeliveryID int64
	)
	cmd := &cobra.Command{
		Use:   "redeliver",
		Short: "Send the stored envelope again, byte for byte.",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().Int64Var(&flagDeliveryID, "delivery-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	_ = cmd.MarkFlagRequired("delivery-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/notifiers/{notifierId}/deliveries/{deliveryId}/redeliver",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		req.PathParams["deliveryId"] = strconv.FormatInt(flagDeliveryID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewNotifiersTestCommand returns the "notifiers test" command (POST
// /api/notifiers/{notifierId}/test).
func NewNotifiersTestCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagNotifierID int64
	)
	cmd := &cobra.Command{
		Use:   "test",
		Short: "Send one delivery now, straight to this notifier. It carries `test: true`.",
	}
	cmd.Flags().Int64Var(&flagNotifierID, "notifier-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("notifier-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "POST",
			Path:       "/api/notifiers/{notifierId}/test",
			PathParams: map[string]string{},
		}
		req.PathParams["notifierId"] = strconv.FormatInt(flagNotifierID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostProbeCommand returns the "host probe" command (GET
// /api/probe/{id}).
func NewHostProbeCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagService string
		flagID      string
	)
	cmd := &cobra.Command{
		Use:   "probe",
		Short: "Is this preview serving? No token, no body — the answer is the status code and `x-pstack-probe`.",
	}
	cmd.Flags().StringVar(&flagService, "service", "", "Which service")
	cmd.Flags().StringVar(&flagID, "id", "", "The registry id, e.g. `pr-123`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/probe/{id}",
			PathParams: map[string]string{},
			Query:      url.Values{},
		}
		if cmd.Flags().Changed("service") {
			req.Query.Set("service", flagService)
		}
		req.PathParams["id"] = flagID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRegistriesListCommand returns the "registries list" command (GET
// /api/registries).
func NewRegistriesListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Private-registry logins. Hostnames only, never a credential.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/registries",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRegistriesDeleteCommand returns the "registries delete" command
// (DELETE /api/registries/{host}).
func NewRegistriesDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagHost string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/registries/{host}",
	}
	cmd.Flags().StringVar(&flagHost, "host", "", "The registry hostname, e.g. `ghcr.io`.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("host")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/registries/{host}",
			PathParams: map[string]string{},
		}
		req.PathParams["host"] = flagHost
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRegistriesPutCommand returns the "registries put" command (PUT
// /api/registries/{host}).
func NewRegistriesPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagHost     string
		bodyUsername string
		bodyPassword string
		flagData     string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "PUT /api/registries/{host}",
	}
	cmd.Flags().StringVar(&flagHost, "host", "", "The registry hostname, e.g. `ghcr.io`.")
	cmd.Flags().StringVar(&bodyUsername, "username", "", "")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("host")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/registries/{host}",
			PathParams: map[string]string{},
		}
		req.PathParams["host"] = flagHost
		body := map[string]any{}
		if cmd.Flags().Changed("username") {
			body["username"] = bodyUsername
		}
		if cmd.Flags().Changed("password") {
			body["password"] = bodyPassword
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRoutingListCommand returns the "routing list" command (GET
// /api/routing).
func NewRoutingListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Traefik's dynamic-config files.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/routing",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRoutingLiveCommand returns the "routing live" command (GET
// /api/routing/live).
func NewRoutingLiveCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "live",
		Short: "Every router Traefik currently knows about.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/routing/live",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRoutingDeleteCommand returns the "routing delete" command (DELETE
// /api/routing/{file}).
func NewRoutingDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagFile string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/routing/{file}",
	}
	cmd.Flags().StringVar(&flagFile, "file", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("file")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/routing/{file}",
			PathParams: map[string]string{},
		}
		req.PathParams["file"] = flagFile
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRoutingGetCommand returns the "routing get" command (GET
// /api/routing/{file}).
func NewRoutingGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagFile string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "GET /api/routing/{file}",
	}
	cmd.Flags().StringVar(&flagFile, "file", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("file")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/routing/{file}",
			PathParams: map[string]string{},
		}
		req.PathParams["file"] = flagFile
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewRoutingPutCommand returns the "routing put" command (PUT
// /api/routing/{file}).
func NewRoutingPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagFile    string
		bodyContent string
		flagData    string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "PUT /api/routing/{file}",
	}
	cmd.Flags().StringVar(&flagFile, "file", "", "")
	cmd.Flags().StringVar(&bodyContent, "content", "", "The file's whole contents.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("file")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/routing/{file}",
			PathParams: map[string]string{},
		}
		req.PathParams["file"] = flagFile
		body := map[string]any{}
		if cmd.Flags().Changed("content") {
			body["content"] = bodyContent
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSettingsListCommand returns the "settings list" command (GET
// /api/settings).
func NewSettingsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Both runtime settings, resolved, each saying which layer it came from.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/settings",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSettingsSetDefaultRoleCommand returns the "settings
// set-default-role" command (PUT /api/settings/default_role).
func NewSettingsSetDefaultRoleCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyValue string
		flagData  string
	)
	cmd := &cobra.Command{
		Use:   "set-default-role",
		Short: "The role an account gets when nothing names one. Admin only.",
	}
	cmd.Flags().StringVar(&bodyValue, "value", "", "(one of: viewer, developer, maintainer, admin)")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("value") {
			if err := oascmd.ValidateEnum("value", []string{"viewer", "developer", "maintainer", "admin"}, bodyValue); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "PUT",
			Path:   "/api/settings/default_role",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("value") {
			body["value"] = bodyValue
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSettingsSetMaxJobsCommand returns the "settings set-max-jobs"
// command (PUT /api/settings/max_jobs).
func NewSettingsSetMaxJobsCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyValue int64
		flagData  string
	)
	cmd := &cobra.Command{
		Use:   "set-max-jobs",
		Short: "How many jobs run at once, host-wide. Maintainer. In force immediately: raising it dispatches what was waiting, lowering it cancels nothing.",
	}
	cmd.Flags().Int64Var(&bodyValue, "value", 0, "A whole number")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "PUT",
			Path:   "/api/settings/max_jobs",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("value") {
			body["value"] = bodyValue
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSpecsListCommand returns the "specs list" command (GET /api/specs).
func NewSpecsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Every named spec.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/specs",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSpecsDeleteCommand returns the "specs delete" command (DELETE
// /api/specs/{name}).
func NewSpecsDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagName string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/specs/{name}",
	}
	cmd.Flags().StringVar(&flagName, "name", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("name")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/specs/{name}",
			PathParams: map[string]string{},
		}
		req.PathParams["name"] = flagName
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSpecsGetCommand returns the "specs get" command (GET
// /api/specs/{name}).
func NewSpecsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagName string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "GET /api/specs/{name}",
	}
	cmd.Flags().StringVar(&flagName, "name", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("name")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/api/specs/{name}",
			PathParams: map[string]string{},
		}
		req.PathParams["name"] = flagName
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSpecsPutCommand returns the "specs put" command (PUT
// /api/specs/{name}).
func NewSpecsPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagName        string
		bodySpec        string
		bodyCompose     string
		bodyDescription string
		flagData        string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "PUT /api/specs/{name}",
	}
	cmd.Flags().StringVar(&flagName, "name", "", "")
	cmd.Flags().StringVar(&bodySpec, "spec", "", "")
	cmd.Flags().StringVar(&bodyCompose, "compose", "", "")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("name")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/specs/{name}",
			PathParams: map[string]string{},
		}
		req.PathParams["name"] = flagName
		body := map[string]any{}
		if cmd.Flags().Changed("spec") {
			body["spec"] = bodySpec
		}
		if cmd.Flags().Changed("compose") {
			body["compose"] = bodyCompose
		}
		if cmd.Flags().Changed("description") {
			body["description"] = bodyDescription
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSsoConfigDeleteCommand returns the "sso config delete" command
// (DELETE /api/sso/config).
func NewSsoConfigDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Forget the only provider. Accounts it created stay.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "DELETE",
			Path:   "/api/sso/config",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSsoConfigGetCommand returns the "sso config get" command (GET
// /api/sso/config).
func NewSsoConfigGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Every provider, the callback URL to paste, and the presets. Never a client secret.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/sso/config",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSsoConfigPutCommand returns the "sso config put" command (PUT
// /api/sso/config).
func NewSsoConfigPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "Create or replace one provider. Admin only.",
	}
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "PUT",
			Path:   "/api/sso/config",
		}
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSsoProviderDeleteCommand returns the "sso provider delete" command
// (DELETE /api/sso/config/{key}).
func NewSsoProviderDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagKey string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/sso/config/{key}",
	}
	cmd.Flags().StringVar(&flagKey, "key", "", "The provider's slug.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("key")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/sso/config/{key}",
			PathParams: map[string]string{},
		}
		req.PathParams["key"] = flagKey
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSsoProviderPutCommand returns the "sso provider put" command (PUT
// /api/sso/config/{key}).
func NewSsoProviderPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagKey  string
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "put",
		Short: "PUT /api/sso/config/{key}",
	}
	cmd.Flags().StringVar(&flagKey, "key", "", "The provider's slug.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("key")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/sso/config/{key}",
			PathParams: map[string]string{},
		}
		req.PathParams["key"] = flagKey
		body := map[string]any{}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSwarmGetCommand returns the "swarm get" command (GET /api/swarm).
func NewSwarmGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "The swarm's nodes and the manager address. Never the join token.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/swarm",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewSwarmJoinCommand returns the "swarm join" command (GET
// /api/swarm/join).
func NewSwarmJoinCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagFormat string
		flagDistro string
	)
	cmd := &cobra.Command{
		Use:   "join",
		Short: "What a new worker runs. THE OUTPUT IS A SECRET — every shape embeds the join token.",
	}
	cmd.Flags().StringVar(&flagFormat, "format", "", "(one of: token, command, script, cloud-config)")
	cmd.Flags().StringVar(&flagDistro, "distro", "", "For `cloud-config`: which Docker install steps to emit.")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("format") {
			if err := oascmd.ValidateEnum("format", []string{"token", "command", "script", "cloud-config"}, flagFormat); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/swarm/join",
			Query:  url.Values{},
		}
		if cmd.Flags().Changed("format") {
			req.Query.Set("format", flagFormat)
		}
		if cmd.Flags().Changed("distro") {
			req.Query.Set("distro", flagDistro)
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewHostTerminalSessionsCommand returns the "host terminal-sessions"
// command (GET /api/terminal-sessions).
func NewHostTerminalSessionsCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "terminal-sessions",
		Short: "Who opened a container shell, when, and against what.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/terminal-sessions",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewTokensListCommand returns the "tokens list" command (GET
// /api/tokens).
func NewTokensListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Your personal API tokens. Hashes are never returned.",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/tokens",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewTokensCreateCommand returns the "tokens create" command (POST
// /api/tokens).
func NewTokensCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyName string
		bodyTTL  string
		flagData string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Mint one. The token itself appears in this response and nowhere else, ever.",
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "")
	cmd.Flags().StringVar(&bodyTTL, "ttl", "", "How long it lives, e.g. `90d`.")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "POST",
			Path:   "/api/tokens",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("name") {
			body["name"] = bodyName
		}
		if cmd.Flags().Changed("ttl") {
			body["ttl"] = bodyTTL
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewTokensDeleteCommand returns the "tokens delete" command (DELETE
// /api/tokens/{tokenId}).
func NewTokensDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagTokenID int64
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /api/tokens/{tokenId}",
	}
	cmd.Flags().Int64Var(&flagTokenID, "token-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("token-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/tokens/{tokenId}",
			PathParams: map[string]string{},
		}
		req.PathParams["tokenId"] = strconv.FormatInt(flagTokenID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUsersListCommand returns the "users list" command (GET /api/users).
func NewUsersListCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "GET /api/users",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/api/users",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUsersCreateCommand returns the "users create" command (POST
// /api/users).
func NewUsersCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyUsername string
		bodyPassword string
		bodyEmail    string
		bodyRole     string
		flagData     string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Admin only. An absent role means the host's `default_role`.",
	}
	cmd.Flags().StringVar(&bodyUsername, "username", "", "")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "")
	cmd.Flags().StringVar(&bodyEmail, "email", "", "")
	cmd.Flags().StringVar(&bodyRole, "role", "", "(one of: viewer, developer, maintainer, admin)")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("role") {
			if err := oascmd.ValidateEnum("role", []string{"viewer", "developer", "maintainer", "admin"}, bodyRole); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "POST",
			Path:   "/api/users",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("username") {
			body["username"] = bodyUsername
		}
		if cmd.Flags().Changed("password") {
			body["password"] = bodyPassword
		}
		if cmd.Flags().Changed("email") {
			body["email"] = bodyEmail
		}
		if cmd.Flags().Changed("role") {
			body["role"] = bodyRole
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUsersDeleteCommand returns the "users delete" command (DELETE
// /api/users/{userId}).
func NewUsersDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagUserID int64
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Admin only. Refused on the last user and the last admin.",
	}
	cmd.Flags().Int64Var(&flagUserID, "user-id", 0, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("user-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/api/users/{userId}",
			PathParams: map[string]string{},
		}
		req.PathParams["userId"] = strconv.FormatInt(flagUserID, 10)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUsersSetRoleCommand returns the "users set-role" command (PATCH
// /api/users/{userId}).
func NewUsersSetRoleCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagUserID int64
		bodyRole   string
		flagData   string
	)
	cmd := &cobra.Command{
		Use:   "set-role",
		Short: "Admin only. Refused on demoting the last admin.",
	}
	cmd.Flags().Int64Var(&flagUserID, "user-id", 0, "")
	cmd.Flags().StringVar(&bodyRole, "role", "", "(one of: viewer, developer, maintainer, admin)")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("user-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("role") {
			if err := oascmd.ValidateEnum("role", []string{"viewer", "developer", "maintainer", "admin"}, bodyRole); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method:     "PATCH",
			Path:       "/api/users/{userId}",
			PathParams: map[string]string{},
		}
		req.PathParams["userId"] = strconv.FormatInt(flagUserID, 10)
		body := map[string]any{}
		if cmd.Flags().Changed("role") {
			body["role"] = bodyRole
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUsersPasswordSetCommand returns the "users password set" command
// (PUT /api/users/{userId}/password).
func NewUsersPasswordSetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagUserID   int64
		bodyPassword string
		flagData     string
	)
	cmd := &cobra.Command{
		Use:   "set",
		Short: "Your own at any role; anybody else's is admin only. Revokes their sessions.",
	}
	cmd.Flags().Int64Var(&flagUserID, "user-id", 0, "")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("user-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "PUT",
			Path:       "/api/users/{userId}/password",
			PathParams: map[string]string{},
		}
		req.PathParams["userId"] = strconv.FormatInt(flagUserID, 10)
		body := map[string]any{}
		if cmd.Flags().Changed("password") {
			body["password"] = bodyPassword
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}
