// Package share is share links: a signed, expiring, READ-ONLY grant to one deployment.
//
// THE PROBLEM. "Can you look at the logs of PR 123?" used to mean creating an account for someone
// who will sign in once. A share link is the account-free answer: a URL that opens that deployment's
// details and log view, and nothing else, until it expires.
//
// ── WHAT IT IS ───────────────────────────────────────────────────────────────────────────────────
//
// An HS256 JWT, signed with PSTACK_TOKEN. No library: a JWT is base64url(header).base64url(claims)
// and an HMAC over those bytes, and this package carries no runtime dependencies. The claims are
// exactly `{ sub: 'share', dep, views, iat, exp }` — which deployment, which views, for how long.
//
// Why PSTACK_TOKEN as the key: it is the one secret the control plane already holds that every host
// has, it is 192 bits when generated by `init`, and `pstack upgrade` deliberately preserves it, so
// links survive upgrades. Rotating it (`PSTACK_TOKEN=… pstack init`) invalidates every link — that IS
// the revocation mechanism, and the only one: nothing about a link is stored (invariant 10 — a table
// of issued links would be a row describing a credential), so there is no per-link revoke. Keep TTLs
// short; the default is 7 days and the ceiling 30.
//
// ── WHERE IT TRAVELS ─────────────────────────────────────────────────────────────────────────────
//
// `?token=<jwt>` in the query string, by design and not as a convenience: the log view FOLLOWS logs
// over an EventSource, and a browser cannot put a header on one. The same constraint is why sessions
// are cookies (api `principal`). The raw PSTACK_TOKEN is never accepted from a query string — a JWT
// in an access log is a bounded, expiring grant; the bearer would be root.
//
// ── WHAT IT MUST NEVER DO ────────────────────────────────────────────────────────────────────────
//
// Act. `principal()` turns a valid token into `{ kind: 'share' }`, and the gate in api allows that
// principal exactly the GET routes its views name, on its deployment only. Request variables are
// ignored for it (a `?PR=8` could otherwise resolve the spec to ANOTHER stack's logs), and
// `mayOpenTerminal` says no by kind before it looks at anything else.
//
// The byte-sensitive part: the HMAC covers `base64url(JSON.stringify(header)).base64url(JSON.stringify(claims))`
// with the claims keys in the order sub,dep,views,iat,exp — the Claims struct's field order, through
// jsonx. Verification recomputes the HMAC over the RECEIVED segments, so a token the TypeScript
// issued verifies here and vice versa.
package share

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"errors"
	"regexp"
	"strings"

	"github.com/samishal1998/preview-stacks/packages/pstack/internal/js"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/jsonx"
	"github.com/samishal1998/preview-stacks/packages/pstack/internal/omap"
)

// View is one of the two read-only surfaces a link can open. Defined here (the TypeScript declared
// it in auth.ts and re-exported it from share.ts) so that auth can import share without a cycle.
type View string

// The views.
const (
	Details View = "details"
	Logs    View = "logs"
)

// Views lists every view, in the order the error messages and the API enumerate them.
var Views = []View{Details, Logs}

// IsView reports whether v names a known view.
func IsView(v string) bool {
	for _, k := range Views {
		if string(k) == v {
			return true
		}
	}
	return false
}

// Claims is the JWT payload. Field order is the wire order — the signature covers these bytes.
type Claims struct {
	Sub string `json:"sub"`
	// Dep is the deployment id (registry's ID alphabet — never a path or a stack name).
	Dep   string `json:"dep"`
	Views []View `json:"views"`
	// Iat and Exp are seconds since the epoch, like every JWT.
	Iat int64 `json:"iat"`
	Exp int64 `json:"exp"`
}

type header struct {
	Alg string `json:"alg"`
	Typ string `json:"typ"`
}

func hmacB64(key, data string) string {
	m := hmac.New(sha256.New, []byte(key))
	m.Write([]byte(data))
	return js.B64URL(m.Sum(nil))
}

// Sign mints a token. ttlMs is clamped by the caller (api); this only refuses nonsense. now is
// epoch milliseconds — the caller passes time.Now().UnixMilli() (the TypeScript defaulted it).
func Sign(key, deployment string, views []View, ttlMs, now int64) (token string, claims *Claims, err error) {
	if key == "" {
		return "", nil, errors.New("share links need PSTACK_TOKEN to sign with")
	}
	sec := floorDiv(now, 1000)
	// `[...new Set(views)]` then filtered to the known ones — first occurrence keeps its place.
	kept := []View{}
	for _, v := range views {
		if !IsView(string(v)) || contains(kept, v) {
			continue
		}
		kept = append(kept, v)
	}
	if len(kept) == 0 {
		return "", nil, errors.New("views must include at least one of: " + strings.Join(viewNames(Views), ", "))
	}
	if !(ttlMs > 0) {
		return "", nil, errors.New("ttl must be positive")
	}
	c := &Claims{Sub: "share", Dep: deployment, Views: kept, Iat: sec, Exp: sec + ceilDiv(ttlMs, 1000)}
	head := js.B64URL(jsonx.Must(header{Alg: "HS256", Typ: "JWT"}))
	body := js.B64URL(jsonx.Must(c))
	return head + "." + body + "." + hmacB64(key, head+"."+body), c, nil
}

var shape = regexp.MustCompile(`^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$`)

// LooksLikeToken: does this string have the shape of a JWT this module issued? Cheap, run before any crypto.
func LooksLikeToken(v string) bool { return shape.MatchString(v) }

// Verify returns the claims, or nil for ANY defect — wrong signature, expired, malformed, not ours.
// One nil rather than a reason: a caller answers 401 either way, and a distinguishable error is an
// oracle nobody needs. now is epoch milliseconds.
func Verify(key, token string, now int64) *Claims {
	if key == "" || !LooksLikeToken(token) {
		return nil
	}
	parts := strings.SplitN(token, ".", 3)
	head, body, sig := parts[0], parts[1], parts[2]
	expected := hmacB64(key, head+"."+body)
	// Length first, then content — and the content compare is constant-time, which the TypeScript's
	// `!==` was not; the result is the same set of accepted tokens.
	if len(sig) != len(expected) || subtle.ConstantTimeCompare([]byte(sig), []byte(expected)) != 1 {
		return nil
	}
	h := decodeObject(head)
	if h == nil || h.GetString("alg") != "HS256" {
		return nil
	}
	c := decodeObject(body)
	if c == nil {
		return nil
	}
	if c.GetString("sub") != "share" {
		return nil
	}
	dep, isStr := c.Get("dep")
	if _, ok := dep.(string); !isStr || !ok {
		return nil
	}
	rawViews, ok := c.Get("views")
	list, isList := rawViews.([]any)
	if !ok || !isList {
		return nil
	}
	exp, okExp := number(c, "exp")
	iat, okIat := number(c, "iat")
	if !okExp || !okIat {
		return nil
	}
	if exp*1000 <= float64(now) {
		return nil
	}
	views := []View{}
	for _, v := range list {
		if s, ok := v.(string); ok && IsView(s) {
			views = append(views, View(s))
		}
	}
	if len(views) == 0 {
		return nil
	}
	return &Claims{Sub: "share", Dep: dep.(string), Views: views, Iat: int64(iat), Exp: int64(exp)}
}

// decodeObject is `JSON.parse(Buffer.from(seg, 'base64url'))` narrowed to an object; nil otherwise.
func decodeObject(seg string) *omap.Map {
	raw, err := js.B64URLDecode(seg)
	if err != nil {
		return nil
	}
	v, err := omap.Parse(raw)
	if err != nil {
		return nil
	}
	m, _ := v.(*omap.Map)
	return m
}

// number is `typeof c[k] === 'number'`.
func number(m *omap.Map, k string) (float64, bool) {
	switch x, _ := m.Get(k); v := x.(type) {
	case int64:
		return float64(v), true
	case float64:
		return v, true
	}
	return 0, false
}

func floorDiv(a, b int64) int64 {
	q := a / b
	if a%b != 0 && (a < 0) != (b < 0) {
		q--
	}
	return q
}

func ceilDiv(a, b int64) int64 {
	q := a / b
	if a%b != 0 && (a < 0) == (b < 0) {
		q++
	}
	return q
}

func contains(list []View, v View) bool {
	for _, x := range list {
		if x == v {
			return true
		}
	}
	return false
}

// viewNames is the list as strings, for messages and for the API's "views are: …" wording.
func viewNames(vs []View) []string {
	out := make([]string, len(vs))
	for i, v := range vs {
		out[i] = string(v)
	}
	return out
}
