/**
 * `pstack build-image` — build the control image from the installed package itself.
 *
 * WHY THIS EXISTS. `pstack init` requires the control image to exist locally and deliberately does
 * not pull. That left a globally-installed pstack in a dead end: the published package ships only
 * `dist/`, so there was no Dockerfile to build from and no registry to pull from — `init` would
 * refuse with "image pstack:local not found" and the operator's only way out was cloning the
 * source. A CLI that cannot produce the one artefact it requires is a broken install.
 *
 * The way out: the Dockerfile INSTALLS THE PUBLISHED PACKAGE inside the build. No checkout, no
 * registry for the image, and — the part that matters — nothing needs to be present on the host
 * beyond docker itself. The build context is empty; the Dockerfile arrives on stdin.
 *
 * That is what makes the advanced UI work too. It is a build-time input to its image, so requiring
 * it to ALSO be installed globally on the host was gratuitous — and on a host where `bun install -g`
 * fails (no global directory), it turned an optional UI into a boot failure.
 *
 * `--dist-dir` / `--ui-dist` keep the old behaviour of building from local files, for developing a
 * change that is not published yet.
 *
 * The generated image is byte-identical in behaviour to the repo's own Dockerfile runtime stage —
 * that file keeps the multi-stage source build for CI and contributors; this is the same final
 * layer, fed from an already-built bundle.
 */

import { cp, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import pkg from '../package.json';
import type { Runner } from './exec.ts';
import { shq } from './compose.ts';

export const DEFAULT_IMAGE_TAG = 'pstack:local';
/** Matches PSTACK_UI_IMAGE's default in `init`, so `build-image --ui` then `init --ui advanced`
 *  need no flags between them. */
export const DEFAULT_UI_IMAGE_TAG = 'pstack-ui:local';


/**
 * The control image, built by installing this exact version from npm.
 *
 * Pinned to the running CLI's version so the image and the CLI that rendered it cannot disagree —
 * an image floating on `latest` would silently drift from the `init` that deployed it.
 *
 * The entry point is the file inside node_modules rather than a global bin: `bun install -g` needs
 * a writable global directory that not every image or host provides, and when it is missing the
 * failure is an opaque "No global directory found" at runtime.
 */
export function controlDockerfile(version = pkg.version): string {
  return `# Generated by \`pstack dockerfile\` (pstack ${version}). Rewritten on every run.
#
# Self-contained: builds with an EMPTY context, so \`docker build -t pstack:local - < this-file\`
# works on a host with nothing but docker.

# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# ~50 MB instead of ~200 MB and no key/repo dance. pstack drives \`docker compose\` by shelling out,
# so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM oven/bun:1

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: \`docker compose\` resolves \`docker-compose\` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \\
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Client-side, needs no daemon: turns a moved upstream path into an obvious build failure rather
# than a runtime one on the host.
RUN docker --version && docker compose version

WORKDIR /app
RUN bun add @samyx/preview-stacks@${version}

# Non-root by default. The control stack overrides it with \`user: "0:0"\` because it mounts the
# Docker socket read-write.
USER bun

EXPOSE 7878

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \\
  CMD ["bun", "node_modules/@samyx/preview-stacks/dist/cli.js", "healthcheck"]

CMD ["bun", "node_modules/@samyx/preview-stacks/dist/cli.js", "serve"]
`;
}

/** The advanced UI image: nginx over the published SPA package. Also builds with an empty context. */
export function uiDockerfile(version = pkg.version): string {
  return `# Generated by \`pstack dockerfile --ui\` (pstack ${version}). Rewritten on every run.
#
# Self-contained: \`docker build -t pstack-ui:local - < this-file\`. The UI package is a BUILD-TIME
# input fetched here, so it never has to be installed on the host.
FROM oven/bun:1 AS fetch
WORKDIR /app
RUN bun add @samyx/preview-stacks-ui@${version}

FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link 404s on reload) and no
# /api/ proxy (every API call would leave the origin and need CORS).
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=fetch /app/node_modules/@samyx/preview-stacks-ui/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`;
}

function localDockerfile(): string {
  return `# Generated by \`pstack build-image\`. Do not edit — it is rewritten on every run.
#
# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# the layer is ~50 MB instead of ~200 MB and needs no key/repo dance. pstack drives \`docker compose\`
# by shelling out, so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM oven/bun:1

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: \`docker compose\` resolves \`docker-compose\` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \\
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Assert it at BUILD time: client-side, needs no daemon, and turns a moved upstream path into an
# obvious build failure instead of a runtime one on the host.
RUN docker --version && docker compose version

WORKDIR /app

# The whole application: one bundle plus its sourcemap. The UI and the control-stack compose
# template are inlined into it as text imports, so there is nothing to keep as a sibling and no
# path resolved relative to source — the failure mode where an image works from a checkout and
# 404s once installed.
COPY dist ./dist

# Non-root by default. The control stack overrides it with \`user: "0:0"\` because it mounts the
# Docker socket read-write.
USER bun

EXPOSE 7878

# Liveness from the API's own route via the CLI's \`healthcheck\` command, so it depends on nothing
# the base image might drop and reads PSTACK_PORT like the server does. \`init\` waits for this to
# report healthy before claiming the control stack is up.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \\
  CMD ["bun", "dist/cli.js", "healthcheck"]

CMD ["bun", "dist/cli.js", "serve"]
`;
}

/** Local-files variant of the UI image, used only with `--ui-dist` (unpublished work in progress). */
function localUiDockerfile(): string {
  return `# Generated by \`pstack build-image --ui\`. Do not edit — rewritten on every run.
FROM nginx:1.27-alpine

# Replaces the stock site: that one has no SPA fallback (every deep link would 404 on reload) and
# no /api/ proxy (every API call would leave the origin and need CORS).
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget -qO- http://127.0.0.1/index.html >/dev/null || exit 1
`;
}

export type BuildImageOptions = {
  tag: string;
  runner: Runner;
  dryRun: boolean;
  /** Build the advanced UI image instead of the control-plane image. */
  ui?: boolean;
  /** Explicit path to a built UI `dist/`, for when the package is installed somewhere unusual. */
  uiDist?: string;
  /**
   * Override the directory copied into the build context. Defaults to this process's own `dist/`.
   *
   * Exists so the logic here — context assembly, the docker invocation, cleanup — can be tested
   * without a build artefact present. A unit test that first requires `bun scripts/build.ts` is
   * order-dependent on a step it does not own, which is exactly how this arrived in CI green
   * locally and red on a clean checkout.
   */
  distDir?: string;
};

/**
 * Assemble a build context from the installed bundle and build the image.
 *
 * The context is a temp directory rather than the install directory: an install may live somewhere
 * read-only (or shared between projects), and writing a Dockerfile into a package's own directory
 * would mutate an installed dependency. It is removed even on failure — a half-built context left
 * in /tmp is the sort of litter nobody goes looking for.
 */
export async function buildImage(opts: BuildImageOptions): Promise<void> {
  const { tag, runner, dryRun, ui } = opts;
  // DEFAULT: no local files at all. The Dockerfile installs the published package itself, so the
  // host needs nothing but docker — no checkout, and no global install of the UI package just to
  // build an image that was going to fetch it anyway.
  const dist = ui ? opts.uiDist : opts.distDir;

  if (dryRun) {
    if (dist) console.log(`  [dry-run] assemble build context from ${dist}`);
    console.log(`  [dry-run] docker image tag ${tag} ${tag}-previous`);
    console.log(`  [dry-run] docker build -t ${tag} <context>`);
    return;
  }

  /*
   * THE ROLLBACK PATH. `docker build -t pstack:local` moves the tag; the image that was running a
   * second ago becomes an anonymous `<none>` layer with no handle. If the new build comes up
   * unhealthy after `init` recreates the stack, the control plane is gone and nothing names the
   * image that worked. Keeping it under `<tag>-previous` makes recovery one line:
   *   docker tag pstack:local-previous pstack:local && docker compose -p pstack-control … up -d
   * Best-effort: on a host with no image yet there is nothing to keep.
   */
  await runner.run(`docker image tag ${shq(tag)} ${shq(`${tag}-previous`)} 2>/dev/null || true`, {
    label: `keep the previous ${tag}`,
  });

  // The Dockerfile is WRITTEN, never interpolated into a command. It is a multi-KB document full of
  // backticks and `$`, and passing it through a shell — even quoted — lets the shell read it: the
  // backticks in its own comments became command substitutions and spliced `docker compose`'s help
  // text into the middle of the file. A build context is a directory; give docker a directory.
  const ctx = await mkdtemp(join(tmpdir(), 'pstack-image-'));
  try {
    if (dist) {
      // ESCAPE HATCH: build from local files, for a change that is not published yet.
      if (ui && !(await Bun.file(join(dist, 'index.html')).exists())) {
        throw new Error(`no built UI at ${dist} — expected an index.html there`);
      }
      await cp(dist, join(ctx, 'dist'), { recursive: true });
      if (ui) {
        // The nginx config sits next to `dist/` in the package, not inside it.
        const conf = join(dist, '..', 'nginx.conf');
        if (!(await Bun.file(conf).exists())) {
          throw new Error(
            `found the UI assets at ${dist} but no nginx.conf beside them — the package is ` +
              `incomplete, so the image would serve the SPA with no /api proxy and no deep-link ` +
              `fallback.`,
          );
        }
        await cp(conf, join(ctx, 'nginx.conf'));
      }
    }

    const df = dist
      ? ui
        ? localUiDockerfile()
        : localDockerfile()
      : ui
        ? uiDockerfile()
        : controlDockerfile();
    await writeFile(join(ctx, 'Dockerfile'), df, 'utf8');

    console.log(dist ? `building ${tag} from ${dist}` : `building ${tag} (pstack ${pkg.version}, from npm)`);
    // `--pull` so a months-old cached `oven/bun:1` does not silently pin an old runtime; the base
    // layers are shared with anything else on the box, so the cost is one manifest check.
    const r = await runner.run(`docker build --pull -t ${JSON.stringify(tag)} ${JSON.stringify(ctx)}`, {
      label: `docker build ${tag}`,
    });
    if (!r.ok) {
      throw new Error(
        `docker build failed (exit ${r.code}).\n${(r.stderr || r.stdout).trim().slice(0, 2000)}`,
      );
    }
    console.log(`built ${tag}`);
    console.log(
      ui
        ? `  next:  pstack init --ui advanced --domain <preview.example.com> --acme-email <you@example.com>`
        : `  next:  pstack init --domain <preview.example.com> --acme-email <you@example.com>`,
    );
  } finally {
    await rm(ctx, { recursive: true, force: true }).catch(() => {});
  }
}
