/**
 * Share links: a signed, expiring, READ-ONLY grant to one deployment.
 *
 * THE PROBLEM. "Can you look at the logs of PR 123?" used to mean creating an account for someone
 * who will sign in once. A share link is the account-free answer: a URL that opens that deployment's
 * details and log view, and nothing else, until it expires.
 *
 * ── WHAT IT IS ───────────────────────────────────────────────────────────────────────────────────
 *
 * An HS256 JWT, signed with PSTACK_TOKEN. No library: a JWT is base64url(header).base64url(claims)
 * and an HMAC over those bytes, and this package carries no runtime dependencies. The claims are
 * exactly `{ sub: 'share', dep, views, iat, exp }` — which deployment, which views, for how long.
 *
 * Why PSTACK_TOKEN as the key: it is the one secret the control plane already holds that every host
 * has, it is 192 bits when generated by `init`, and `pstack upgrade` deliberately preserves it, so
 * links survive upgrades. Rotating it (`PSTACK_TOKEN=… pstack init`) invalidates every link — that IS
 * the revocation mechanism, and the only one: nothing about a link is stored (invariant 10 — a table
 * of issued links would be a row describing a credential), so there is no per-link revoke. Keep TTLs
 * short; the default is 7 days and the ceiling 30.
 *
 * ── WHERE IT TRAVELS ─────────────────────────────────────────────────────────────────────────────
 *
 * `?token=<jwt>` in the query string, by design and not as a convenience: the log view FOLLOWS logs
 * over an EventSource, and a browser cannot put a header on one. The same constraint is why sessions
 * are cookies (api.ts `principal`). The raw PSTACK_TOKEN is never accepted from a query string — a
 * JWT in an access log is a bounded, expiring grant; the bearer would be root.
 *
 * ── WHAT IT MUST NEVER DO ────────────────────────────────────────────────────────────────────────
 *
 * Act. `principal()` turns a valid token into `{ kind: 'share' }`, and the gate in api.ts allows that
 * principal exactly the GET routes its views name, on its deployment only. Request variables are
 * ignored for it (a `?PR=8` could otherwise resolve the spec to ANOTHER stack's logs), and
 * `mayOpenTerminal` says no by kind before it looks at anything else.
 */

import type { ShareView } from './auth.ts';

export type { ShareView } from './auth.ts';

export const SHARE_VIEWS: readonly ShareView[] = ['details', 'logs'] as const;

export type ShareClaims = {
  sub: 'share';
  /** Deployment id (registry.ts `ID` alphabet — never a path or a stack name). */
  dep: string;
  views: ShareView[];
  /** Seconds since the epoch, like every JWT. */
  iat: number;
  exp: number;
};

const b64url = (bytes: Uint8Array | string): string => {
  const b = typeof bytes === 'string' ? Buffer.from(bytes, 'utf8') : Buffer.from(bytes);
  return b.toString('base64url');
};

function hmac(key: string, data: string): string {
  return b64url(new Bun.CryptoHasher('sha256', key).update(data).digest());
}

/** Sign. `ttlMs` is clamped by the caller (api.ts); this only refuses nonsense. */
export function signShare(
  key: string,
  args: { deployment: string; views: ShareView[]; ttlMs: number; now?: number },
): { token: string; claims: ShareClaims } {
  if (!key) throw new Error('share links need PSTACK_TOKEN to sign with');
  const now = Math.floor((args.now ?? Date.now()) / 1000);
  const views = [...new Set(args.views)].filter((v): v is ShareView => (SHARE_VIEWS as readonly string[]).includes(v));
  if (views.length === 0) throw new Error(`views must include at least one of: ${SHARE_VIEWS.join(', ')}`);
  if (!(args.ttlMs > 0)) throw new Error('ttl must be positive');
  const claims: ShareClaims = {
    sub: 'share',
    dep: args.deployment,
    views,
    iat: now,
    exp: now + Math.ceil(args.ttlMs / 1000),
  };
  const head = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = b64url(JSON.stringify(claims));
  return { token: `${head}.${body}.${hmac(key, `${head}.${body}`)}`, claims };
}

/** Does this string have the shape of a JWT this module issued? Cheap, run before any crypto. */
export function looksLikeShareToken(v: string): boolean {
  return /^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(v);
}

/**
 * Verify. Returns the claims, or null for ANY defect — wrong signature, expired, malformed, not ours.
 * One null rather than a reason: a caller answers 401 either way, and a distinguishable error is an
 * oracle nobody needs.
 */
export function verifyShare(key: string, token: string, now: number = Date.now()): ShareClaims | null {
  if (!key || !looksLikeShareToken(token)) return null;
  const [head, body, sig] = token.split('.') as [string, string, string];
  const expected = hmac(key, `${head}.${body}`);
  // Length first, then content — the same discipline as the bearer compare in api.ts.
  if (sig.length !== expected.length || sig !== expected) return null;
  let claims: unknown;
  try {
    const h = JSON.parse(Buffer.from(head, 'base64url').toString('utf8')) as { alg?: unknown };
    if (h.alg !== 'HS256') return null;
    claims = JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
  } catch {
    return null;
  }
  if (!claims || typeof claims !== 'object') return null;
  const c = claims as Record<string, unknown>;
  if (c.sub !== 'share' || typeof c.dep !== 'string' || !Array.isArray(c.views)) return null;
  if (typeof c.exp !== 'number' || typeof c.iat !== 'number') return null;
  if (c.exp * 1000 <= now) return null;
  const views = c.views.filter((v): v is ShareView => (SHARE_VIEWS as readonly string[]).includes(v as string));
  if (views.length === 0) return null;
  return { sub: 'share', dep: c.dep, views, iat: c.iat, exp: c.exp };
}
