// SHELL COMPLETION — `pstack completion bash|zsh|fish`.
//
// Generated from the same table `pstack <cmd> --help` reads (commands.go), so a flag the shell
// offers is a flag the help describes. A hand-written completion script is the classic thing that
// rots: nobody notices a MISSING completion (it reads as "my shell needs reloading"), so it drifts
// silently until it is wrong about everything.
//
// STATIC ONLY, deliberately. A shell could complete deployment ids by calling the API, but that
// would mean every TAB press making an authenticated HTTP request to a host that may be down,
// slow, or not configured in this terminal — a shell that hangs on TAB is worse than one that
// completes nothing. Commands, subcommands and flags are what a shell can know for free.
package cli

import (
	"fmt"
	"sort"
	"strings"
)

// Shells is what `completion` accepts, in the order the usage lists them.
var Shells = []string{"bash", "zsh", "fish"}

// Completion is the script for one shell, or a usage error naming the ones that exist.
func Completion(shell string) (string, *Exit) {
	switch shell {
	case "bash":
		return bashCompletion(), nil
	case "zsh":
		return zshCompletion(), nil
	case "fish":
		return fishCompletion(), nil
	}
	return "", fail("unknown shell \"" + shell + "\" — pstack completion " + strings.Join(Shells, "|"))
}

// subcommands are the second words a command takes. Not in commandHelps because they are not
// flags and only three commands have any.
var subcommands = map[string][]string{
	"ui":         {"basic", "advanced"},
	"swarm":      {"status", "join"},
	"pull":       {"config"},
	"push":       {"config"},
	"completion": Shells,
}

// enumFlags are the flags whose VALUES are a closed set — the ones worth completing, because a
// wrong value is a usage error the shell could have prevented.
var enumFlags = map[string][]string{
	"--challenge":    {"http01", "dns01"},
	"--ui":           {"basic", "advanced"},
	"--orchestrator": {"swarm", "compose"},
	"--distro":       {"ubuntu", "debian", "fedora", "suse", "arch", "alpine"},
	"--format":       {"command", "script", "cloud-config", "token"},
}

// zshQuote wraps a value in single quotes, ending and reopening them around any it contains —
// the only escape a POSIX-ish shell offers inside single quotes.
func zshQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}

func sortedCommands() []string {
	out := append([]string{}, Commands...)
	out = append(out, "completion")
	sort.Strings(out)
	return out
}

func bashCompletion() string {
	var b strings.Builder
	b.WriteString(`# pstack bash completion. Generated by ` + "`pstack completion bash`" + ` — do not edit.
#   pstack completion bash > /etc/bash_completion.d/pstack        (system)
#   pstack completion bash > ~/.local/share/bash-completion/completions/pstack
_pstack() {
  local cur prev cmd i
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cmd=""
  for ((i=1; i<COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      -*) ;;
      *) if [ -z "$cmd" ]; then cmd="${COMP_WORDS[i]}"; fi ;;
    esac
  done

  # A flag whose values are a closed set completes to that set.
  case "$prev" in
`)
	keys := make([]string, 0, len(enumFlags))
	for k := range enumFlags {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, f := range keys {
		fmt.Fprintf(&b, "    %s) COMPREPLY=($(compgen -W %q -- \"$cur\")); return ;;\n", f, strings.Join(enumFlags[f], " "))
	}
	b.WriteString(`    --file|-f|-o|-i|--config|--dns-token-file|--ui-dist) COMPREPLY=($(compgen -f -- "$cur")); return ;;
  esac

  if [ -z "$cmd" ]; then
    COMPREPLY=($(compgen -W ` + fmt.Sprintf("%q", strings.Join(sortedCommands(), " ")) + ` -- "$cur"))
    return
  fi

  case "$cmd" in
`)
	for _, c := range sortedCommands() {
		words := append([]string{}, subcommands[c]...)
		words = append(words, completionFlags(c)...)
		fmt.Fprintf(&b, "    %s) COMPREPLY=($(compgen -W %q -- \"$cur\")) ;;\n", c, strings.Join(words, " "))
	}
	b.WriteString(`  esac
}
complete -F _pstack pstack
`)
	return b.String()
}

func zshCompletion() string {
	var b strings.Builder
	b.WriteString(`#compdef pstack
# pstack zsh completion. Generated by ` + "`pstack completion zsh`" + ` — do not edit.
#   pstack completion zsh > "${fpath[1]}/_pstack"   then restart the shell
_pstack() {
  local -a commands
  commands=(
`)
	for _, c := range sortedCommands() {
		summary := ""
		if h, ok := commandHelps[c]; ok {
			summary = h.summary
		} else if c == "completion" {
			summary = "print a shell completion script"
		}
		// zsh shows the description beside the command, which is the whole reason the table carries
		// a one-liner per command. SINGLE-QUOTED: an unquoted entry is parsed as ordinary shell
		// words, so a summary containing `<` (as `ui`'s does) is a redirection and the whole script
		// fails to parse — which a completion script does silently.
		fmt.Fprintf(&b, "    %s\n", zshQuote(c+":"+strings.ReplaceAll(summary, ":", " —")))
	}
	b.WriteString(`  )
  if (( CURRENT == 2 )); then
    _describe 'pstack command' commands
    return
  fi
  local cmd=${words[2]}
  case $cmd in
`)
	for _, c := range sortedCommands() {
		words := append([]string{}, subcommands[c]...)
		words = append(words, completionFlags(c)...)
		fmt.Fprintf(&b, "    %s) compadd %s ;;\n", c, strings.Join(words, " "))
	}
	b.WriteString(`  esac
}
_pstack "$@"
`)
	return b.String()
}

func fishCompletion() string {
	var b strings.Builder
	b.WriteString("# pstack fish completion. Generated by `pstack completion fish` — do not edit.\n" +
		"#   pstack completion fish > ~/.config/fish/completions/pstack.fish\n" +
		"complete -c pstack -f\n")
	for _, c := range sortedCommands() {
		summary := "print a shell completion script"
		if h, ok := commandHelps[c]; ok {
			summary = h.summary
		}
		fmt.Fprintf(&b, "complete -c pstack -n __fish_use_subcommand -a %s -d %q\n", c, summary)
	}
	for _, c := range sortedCommands() {
		for _, s := range subcommands[c] {
			fmt.Fprintf(&b, "complete -c pstack -n '__fish_seen_subcommand_from %s' -a %s\n", c, s)
		}
		for _, f := range completionFlags(c) {
			fmt.Fprintf(&b, "complete -c pstack -n '__fish_seen_subcommand_from %s' -l %s\n", c, strings.TrimPrefix(f, "--"))
		}
	}
	return b.String()
}
