/**
 * `pstack build-image` — build the control image from the installed package itself.
 *
 * WHY THIS EXISTS. `pstack init` requires the control image to exist locally and deliberately does
 * not pull. That left a globally-installed pstack in a dead end: the published package ships only
 * `dist/`, so there was no Dockerfile to build from and no registry to pull from — `init` would
 * refuse with "image pstack:local not found" and the operator's only way out was cloning the
 * source. A CLI that cannot produce the one artefact it requires is a broken install.
 *
 * The way out is that `dist/` IS the whole application. The runtime image needs nothing else from
 * the repo, so the build context can be assembled from the installed files plus a Dockerfile
 * generated here. No checkout, no registry, no publish step.
 *
 * The generated image is byte-identical in behaviour to the repo's own Dockerfile runtime stage —
 * that file keeps the multi-stage source build for CI and contributors; this is the same final
 * layer, fed from an already-built bundle.
 */

import { cp, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { Runner } from './exec.ts';

export const DEFAULT_IMAGE_TAG = 'pstack:local';

/**
 * Where this process's `dist/` lives.
 *
 * When running from the published bundle, `import.meta.url` is `…/dist/cli.js`, so its directory IS
 * dist. When running from source (`bun src/cli.ts`), it is `…/src/image.ts`, and dist is a sibling
 * that may not have been built yet — hence the existence check, which turns a confusing
 * "COPY failed" from Docker into an actionable message.
 */
async function findDist(): Promise<string> {
  const here = new URL('.', import.meta.url).pathname;
  const candidates = [here, join(here, '..', 'dist')];
  for (const dir of candidates) {
    if (await Bun.file(join(dir, 'cli.js')).exists()) return dir;
  }
  throw new Error(
    `could not find the built bundle next to ${here}. If you are running from a source checkout, ` +
      `build it first:  bun scripts/build.ts`,
  );
}

/**
 * The runtime Dockerfile.
 *
 * Kept in lockstep with the runtime stage of the repo's Dockerfile — if you change one, change both.
 * The comments matter as much here as there: each line encodes a failure someone already hit.
 */
function dockerfile(): string {
  return `# Generated by \`pstack build-image\`. Do not edit — it is rewritten on every run.
#
# The docker CLI + compose plugin, lifted from the official image rather than installed from apt:
# the layer is ~50 MB instead of ~200 MB and needs no key/repo dance. pstack drives \`docker compose\`
# by shelling out, so without these the API starts fine and every operation fails.
FROM docker:28-cli AS docker-cli

FROM oven/bun:1

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
# Compose is a CLI *plugin*: \`docker compose\` resolves \`docker-compose\` out of the plugin
# directory, so copying only the binary yields "docker: 'compose' is not a docker command".
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose \\
                       /usr/local/libexec/docker/cli-plugins/docker-compose

# Assert it at BUILD time: client-side, needs no daemon, and turns a moved upstream path into an
# obvious build failure instead of a runtime one on the host.
RUN docker --version && docker compose version

WORKDIR /app

# The whole application: one bundle plus its sourcemap. The UI and the control-stack compose
# template are inlined into it as text imports, so there is nothing to keep as a sibling and no
# path resolved relative to source — the failure mode where an image works from a checkout and
# 404s once installed.
COPY dist ./dist

# Non-root by default. The control stack overrides it with \`user: "0:0"\` because it mounts the
# Docker socket read-write.
USER bun

EXPOSE 7878

# Liveness from the API's own route, written in Bun so it depends on nothing the base image might
# drop, and reading PSTACK_PORT so a non-default port still works. \`init\` waits for this to report
# healthy before claiming the control stack is up.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \\
  CMD ["bun", "--eval", "const r = await fetch('http://127.0.0.1:' + (process.env.PSTACK_PORT ?? 7878) + '/api/health'); process.exit(r.ok ? 0 : 1)"]

CMD ["bun", "dist/cli.js", "serve"]
`;
}

export type BuildImageOptions = {
  tag: string;
  runner: Runner;
  dryRun: boolean;
};

/**
 * Assemble a build context from the installed bundle and build the image.
 *
 * The context is a temp directory rather than the install directory: an install may live somewhere
 * read-only (or shared between projects), and writing a Dockerfile into a package's own directory
 * would mutate an installed dependency. It is removed even on failure — a half-built context left
 * in /tmp is the sort of litter nobody goes looking for.
 */
export async function buildImage(opts: BuildImageOptions): Promise<void> {
  const { tag, runner, dryRun } = opts;
  const dist = await findDist();

  if (dryRun) {
    console.log(`  [dry-run] assemble build context from ${dist}`);
    console.log(`  [dry-run] docker build -t ${tag} <context>`);
    return;
  }

  const ctx = await mkdtemp(join(tmpdir(), 'pstack-image-'));
  try {
    await cp(dist, join(ctx, 'dist'), { recursive: true });
    await writeFile(join(ctx, 'Dockerfile'), dockerfile(), 'utf8');

    console.log(`building ${tag} from ${dist}`);
    // `--pull` so a months-old cached `oven/bun:1` does not silently pin an old runtime; the base
    // layers are shared with anything else on the box, so the cost is one manifest check.
    const r = await runner.run(`docker build --pull -t ${JSON.stringify(tag)} ${JSON.stringify(ctx)}`, {
      label: `docker build ${tag}`,
    });
    if (!r.ok) {
      throw new Error(
        `docker build failed (exit ${r.code}).\n${(r.stderr || r.stdout).trim().slice(0, 2000)}`,
      );
    }
    console.log(`built ${tag}`);
    console.log(`  next:  pstack init --domain <preview.example.com> --acme-email <you@example.com>`);
  } finally {
    await rm(ctx, { recursive: true, force: true }).catch(() => {});
  }
}
